In [1]:
# ============================================================
# 06_IDEAL_SIMULATION.ipynb
# IDEAL VQC SIMULATION
# ============================================================

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from qiskit_aer import AerSimulator

print("=" * 60)
print("IDEAL VQC SIMULATION")
print("=" * 60)

============================================================
IDEAL VQC SIMULATION
============================================================

In [2]:
# ============================================================
# PROJECT CONFIGURATION
# ============================================================

PROJECT_ROOT = Path(r"C:\Users\heart\quantum_6g_ai")

RESULTS_DIR = PROJECT_ROOT / "results"
FIGURES_DIR = RESULTS_DIR / "figures"

RESULTS_DIR.mkdir(parents=True, exist_ok=True)
FIGURES_DIR.mkdir(parents=True, exist_ok=True)

THETA_FILE = RESULTS_DIR / "trained_theta.npy"

print("Project Root :", PROJECT_ROOT)
print("Results Dir  :", RESULTS_DIR)
print("Figures Dir  :", FIGURES_DIR)
print("Theta File   :", THETA_FILE)

Project Root : C:\Users\heart\quantum_6g_ai
Results Dir  : C:\Users\heart\quantum_6g_ai\results
Figures Dir  : C:\Users\heart\quantum_6g_ai\results\figures
Theta File   : C:\Users\heart\quantum_6g_ai\results\trained_theta.npy

In [3]:
# ============================================================
# EXPERIMENT PARAMETERS
# ============================================================

N_QUBITS = 4
N_LAYERS = 2
N_PARAMS = 16
SHOTS = 1024

SEED_SIMULATOR = 42

print("Qubits             :", N_QUBITS)
print("VQC layers         :", N_LAYERS)
print("Parameters         :", N_PARAMS)
print("Shots              :", SHOTS)
print("Simulator seed     :", SEED_SIMULATOR)
print("Noise              : OFF")

Qubits             : 4
VQC layers         : 2
Parameters         : 16
Shots              : 1024
Simulator seed     : 42
Noise              : OFF

In [4]:
# ============================================================
# LOAD TRAINED PARAMETERS
# ============================================================

if not THETA_FILE.exists():
    raise FileNotFoundError(
        f"\nTrained parameters not found:\n{THETA_FILE}\n"
        "\nRun 05_vqc_training.ipynb first."
    )

theta = np.load(THETA_FILE)

print("=" * 60)
print("TRAINED PARAMETERS")
print("=" * 60)

print("Shape :", theta.shape)
print("Count :", len(theta))
print("Min   :", theta.min())
print("Max   :", theta.max())
print("Mean  :", theta.mean())
print("Std   :", theta.std())

============================================================
TRAINED PARAMETERS
============================================================
Shape : (16,)
Count : 16
Min   : -0.712961678257322
Max   : 3.076039906062166
Mean  : 0.1772978436178986
Std   : 0.8534418022550907

In [5]:
# ============================================================
# LOAD TEST DATA
# ============================================================

X_TEST_FILE = RESULTS_DIR / "X_test.npy"
Y_TEST_FILE = RESULTS_DIR / "y_test.npy"

if not X_TEST_FILE.exists():
    raise FileNotFoundError(
        f"Test feature file not found:\n{X_TEST_FILE}\n"
        "\nUse the same X_test generated in 02_preprocessing.ipynb."
    )

if not Y_TEST_FILE.exists():
    raise FileNotFoundError(
        f"Test label file not found:\n{Y_TEST_FILE}\n"
        "\nUse the same y_test generated in 02_preprocessing.ipynb."
    )

X_test = np.load(X_TEST_FILE)
y_test = np.load(Y_TEST_FILE)

print("=" * 60)
print("TEST DATA")
print("=" * 60)

print("X_test shape :", X_test.shape)
print("y_test shape :", y_test.shape)
print("Samples      :", len(y_test))

FileNotFoundError: Test feature file not found:
C:\Users\heart\quantum_6g_ai\results\X_test.npy

Use the same X_test generated in 02_preprocessing.ipynb.

In [ ]:
# ============================================================
# VALIDATION
# ============================================================

if len(theta) != N_PARAMS:
    raise ValueError(
        f"Expected {N_PARAMS} parameters, "
        f"but found {len(theta)}."
    )

if len(X_test) != len(y_test):
    raise ValueError(
        "X_test and y_test have different numbers of samples."
    )

print("Parameter validation : PASS")
print("Dataset validation   : PASS")

In [ ]:
# ============================================================
# IDEAL AER SIMULATOR
# ============================================================

simulator = AerSimulator(
    seed_simulator=SEED_SIMULATOR
)

print("=" * 60)
print("IDEAL SIMULATOR")
print("=" * 60)

print("Backend :", simulator.name)
print("Noise   : OFF")
print("Shots   :", SHOTS)

In [ ]:
# ============================================================
# VQC CIRCUIT
# ============================================================

from qiskit import QuantumCircuit

def build_vqc(x, theta):
    qc = QuantumCircuit(N_QUBITS)

    # --------------------------------------------------------
    # IMPORTANT:
    # Replace this section with the EXACT circuit used in
    # 05_vqc_training.ipynb.
    # --------------------------------------------------------

    # Example feature encoding
    for q in range(N_QUBITS):
        qc.ry(float(x[q]), q)

    # Example variational layers
    index = 0

    for layer in range(N_LAYERS):

        for q in range(N_QUBITS):
            qc.ry(float(theta[index]), q)
            index += 1

        for q in range(N_QUBITS - 1):
            qc.cx(q, q + 1)

    qc.measure_all()

    return qc

In [ ]:
# ============================================================
# PREDICTION FROM COUNTS
# ============================================================

def prediction_from_counts(counts):
    """
    Convert measurement counts into a binary prediction.

    IMPORTANT:
    Replace this logic with the EXACT prediction rule
    used in 05_vqc_training.ipynb.
    """

    total_shots = sum(counts.values())

    probability_1 = sum(
        count
        for bitstring, count in counts.items()
        if bitstring[-1] == "1"
    ) / total_shots

    prediction = 1 if probability_1 >= 0.5 else 0

    return prediction, probability_1

In [ ]:
# ============================================================
# 06 - IDEAL SIMULATION
# ============================================================

from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from qiskit_aer import AerSimulator

print("06 - Ideal Simulation")
print("Imports: OK")

In [ ]:
# ============================================================
# PROJECT CONFIGURATION
# ============================================================

PROJECT_ROOT = Path(r"C:\Users\heart\quantum_6g_ai")

RESULTS_DIR = PROJECT_ROOT / "results"
FIGURES_DIR = RESULTS_DIR / "figures"

RESULTS_DIR.mkdir(parents=True, exist_ok=True)
FIGURES_DIR.mkdir(parents=True, exist_ok=True)

THETA_FILE = RESULTS_DIR / "trained_theta.npy"

print("=" * 60)
print("PROJECT CONFIGURATION")
print("=" * 60)

print("PROJECT_ROOT :", PROJECT_ROOT)
print("RESULTS_DIR  :", RESULTS_DIR)
print("THETA_FILE   :", THETA_FILE)
print("Exists       :", THETA_FILE.exists())

In [ ]:
# ============================================================
# LOAD TRAINED PARAMETERS
# ============================================================

if not THETA_FILE.exists():
    raise FileNotFoundError(
        f"\nTrained parameters not found:\n{THETA_FILE}\n"
        "\nRun 05_vqc_training.ipynb first."
    )

theta = np.load(THETA_FILE)

print("=" * 60)
print("TRAINED PARAMETERS LOADED")
print("=" * 60)

print("Shape :", theta.shape)
print("Count :", len(theta))
print("Min   :", theta.min())
print("Max   :", theta.max())
print("Mean  :", theta.mean())
print("Std   :", theta.std())

In [ ]:
# ============================================================
# CHECK RESULTS DIRECTORY
# ============================================================

print("=" * 60)
print("RESULTS DIRECTORY")
print("=" * 60)

for p in sorted(RESULTS_DIR.iterdir()):
    print(p.name)

In [ ]:
# ============================================================
# INSPECT QUANTUM TEST DATA
# ============================================================

QUANTUM_TEST_FILE = RESULTS_DIR / "quantum_test_features.csv"

if not QUANTUM_TEST_FILE.exists():
    raise FileNotFoundError(
        f"Quantum test feature file not found:\n{QUANTUM_TEST_FILE}"
    )

quantum_test = pd.read_csv(QUANTUM_TEST_FILE)

print("=" * 60)
print("QUANTUM TEST DATA")
print("=" * 60)

print("File   :", QUANTUM_TEST_FILE)
print("Shape  :", quantum_test.shape)

print("\nColumns:")
print(list(quantum_test.columns))

print("\nFirst 5 rows:")
display(quantum_test.head())

print("\nData types:")
print(quantum_test.dtypes)

In [ ]:
# ============================================================
# INSPECT 05 VQC TRAINING NOTEBOOK
# ============================================================

import json

VQC_NOTEBOOK = PROJECT_ROOT / "05_vqc_training.ipynb"

with open(VQC_NOTEBOOK, "r", encoding="utf-8") as f:
    nb05 = json.load(f)

print("=" * 60)
print("05 VQC TRAINING NOTEBOOK")
print("=" * 60)

print("Notebook :", VQC_NOTEBOOK)
print("Cells    :", len(nb05["cells"]))

keywords = [
    "QuantumCircuit",
    "build_vqc",
    "circuit",
    "theta",
    "counts",
    "predict",
    "AerSimulator",
    "measure",
    "angle",
    "ry",
    "rx",
    "rz",
]

for i, cell in enumerate(nb05["cells"]):
    source = "".join(cell.get("source", []))
    
    if any(k.lower() in source.lower() for k in keywords):
        print("\n" + "=" * 60)
        print(f"CELL {i} | {cell['cell_type']}")
        print("=" * 60)
        print(source[:10000])

In [ ]:
# ============================================================
# 06 - IDEAL SIMULATION
# LOAD TEST DATA + EXACT VQC IMPLEMENTATION
# ============================================================

from qiskit import QuantumCircuit, transpile
from qiskit.circuit import ParameterVector
from qiskit_aer import AerSimulator

# ------------------------------------------------------------
# 1. Experiment configuration
# ------------------------------------------------------------

N_QUBITS = 4
N_LAYERS = 2
N_PARAMS = N_QUBITS * 2 * N_LAYERS

SHOTS = 1024
SEED_SIMULATOR = 42

QUANTUM_FEATURES = [
    "Trust_Score",
    "Risk_Score",
    "Interference",
    "Resource_Load"
]

TARGET_COLUMN = "Label"

print("=" * 60)
print("06 - IDEAL SIMULATION CONFIGURATION")
print("=" * 60)

print("Qubits     :", N_QUBITS)
print("VQC layers :", N_LAYERS)
print("Parameters :", N_PARAMS)
print("Shots      :", SHOTS)
print("Seed       :", SEED_SIMULATOR)

In [ ]:
# ============================================================
# LOAD QUANTUM TEST DATA
# ============================================================

QUANTUM_TEST_FILE = RESULTS_DIR / "quantum_test_features.csv"

if not QUANTUM_TEST_FILE.exists():
    raise FileNotFoundError(
        f"Test dataset not found:\n{QUANTUM_TEST_FILE}"
    )

test_q = pd.read_csv(QUANTUM_TEST_FILE)

X_test_q = test_q[QUANTUM_FEATURES].to_numpy(dtype=float)
y_test = test_q[TARGET_COLUMN].to_numpy(dtype=int)

print("=" * 60)
print("IDEAL SIMULATION TEST DATA")
print("=" * 60)

print("File           :", QUANTUM_TEST_FILE)
print("Samples        :", len(X_test_q))
print("Feature shape  :", X_test_q.shape)
print("Labels shape   :", y_test.shape)

print("\nLabel distribution:")
print(pd.Series(y_test).value_counts().sort_index())

assert X_test_q.shape == (200, 4)
assert y_test.shape == (200,)

print("\nValidation: PASS")

In [ ]:
# ============================================================
# EXACT VQC CIRCUIT FROM 05_vqc_training.ipynb
# ============================================================

theta = ParameterVector(
    "θ",
    length=N_PARAMS
)


def build_vqc(
    feature_angles,
    n_qubits=4,
    n_layers=2
):
    """
    Exact VQC architecture used in 05_vqc_training.ipynb.

    Feature encoding:
        Ry(x) + Rz(x)

    Feature-map entanglement:
        Linear CNOT

    Variational layers:
        Ry(theta) + Rz(theta)

    Variational entanglement:
        Linear CNOT
    """

    qc = QuantumCircuit(n_qubits)

    # --------------------------------------------------------
    # Feature encoding
    # --------------------------------------------------------

    for qubit, angle in enumerate(feature_angles):

        qc.ry(angle, qubit)
        qc.rz(angle, qubit)

    # --------------------------------------------------------
    # Feature-map entanglement
    # --------------------------------------------------------

    for qubit in range(n_qubits - 1):

        qc.cx(
            qubit,
            qubit + 1
        )

    # --------------------------------------------------------
    # Variational layers
    # --------------------------------------------------------

    parameter_index = 0

    for layer in range(n_layers):

        for qubit in range(n_qubits):

            qc.ry(
                theta[parameter_index],
                qubit
            )

            parameter_index += 1

            qc.rz(
                theta[parameter_index],
                qubit
            )

            parameter_index += 1

        # Variational entanglement
        for qubit in range(n_qubits - 1):

            qc.cx(
                qubit,
                qubit + 1
            )

    return qc


print("=" * 60)
print("VQC FUNCTION READY")
print("=" * 60)

print("Qubits     :", N_QUBITS)
print("Layers     :", N_LAYERS)
print("Parameters :", len(theta))

assert len(theta) == 16

print("\nValidation: PASS")

In [ ]:
# ============================================================
# IDEAL AER SIMULATOR
# ============================================================

simulator = AerSimulator()

print("=" * 60)
print("IDEAL AER SIMULATOR")
print("=" * 60)

print("Simulator :", simulator.name)
print("Noise     : OFF")
print("Shots     :", SHOTS)
print("Seed      :", SEED_SIMULATOR)

print("\nValidation: PASS")

In [ ]:
# ============================================================
# IDEAL VQC INFERENCE
# NO RETRAINING
# ============================================================

def vqc_probability(
    feature_angles,
    parameter_values,
    shots=1024,
    seed=42
):
    """
    Exact inference logic from 05_vqc_training.ipynb.

    Returns:
        P(y=1)
    """

    # Build exact VQC
    circuit = build_vqc(
        feature_angles,
        n_qubits=N_QUBITS,
        n_layers=N_LAYERS
    )

    # --------------------------------------------------------
    # Bind trained parameters
    # --------------------------------------------------------

    parameter_dict = {
        theta[i]: parameter_values[i]
        for i in range(len(parameter_values))
    }

    circuit = circuit.assign_parameters(parameter_dict)

    # --------------------------------------------------------
    # Measurement
    # --------------------------------------------------------

    circuit.measure_all()

    # --------------------------------------------------------
    # Transpile
    # --------------------------------------------------------

    compiled = transpile(
        circuit,
        simulator,
        optimization_level=1
    )

    # --------------------------------------------------------
    # Ideal execution
    # --------------------------------------------------------

    job = simulator.run(
        compiled,
        shots=shots,
        seed_simulator=seed
    )

    result = job.result()
    counts = result.get_counts()

    # --------------------------------------------------------
    # q0 = 1 probability
    # --------------------------------------------------------

    p1 = 0.0

    for bitstring, count in counts.items():

        q0_bit = int(bitstring[-1])

        if q0_bit == 1:

            p1 += count / shots

    return p1


# ============================================================
# RUN TEST SET
# ============================================================

ideal_probabilities = []
ideal_predictions = []

print("=" * 60)
print("RUNNING IDEAL VQC INFERENCE")
print("=" * 60)

print("Test samples :", len(X_test_q))
print("Shots        :", SHOTS)

for i, feature_angles in enumerate(X_test_q):

    sample_seed = SEED_SIMULATOR + i

    probability = vqc_probability(
        feature_angles,
        theta,
        shots=SHOTS,
        seed=sample_seed
    )

    prediction = int(probability >= 0.5)

    ideal_probabilities.append(probability)
    ideal_predictions.append(prediction)

    if (i + 1) % 25 == 0:
        print(
            f"Processed {i + 1:03d}/{len(X_test_q)} samples"
        )

ideal_probabilities = np.asarray(
    ideal_probabilities,
    dtype=float
)

ideal_predictions = np.asarray(
    ideal_predictions,
    dtype=int
)

print("\nInference complete.")

print("Probability shape :", ideal_probabilities.shape)
print("Prediction shape  :", ideal_predictions.shape)

assert len(ideal_probabilities) == 200
assert len(ideal_predictions) == 200

print("\nValidation: PASS")

In [ ]:
# ============================================================
# FIXED VQC INFERENCE FUNCTION
# QISKIT PARAMETER-BINDING VALIDATION
# ============================================================

def vqc_probability(
    feature_angles,
    parameter_values,
    shots=1024,
    seed=42
):
    """
    Exact VQC architecture from 05_vqc_training.ipynb.

    Returns:
        P(y=1)
    """

    # --------------------------------------------------------
    # 1. Build VQC
    # --------------------------------------------------------

    circuit = build_vqc(
        feature_angles,
        n_qubits=N_QUBITS,
        n_layers=N_LAYERS
    )

    # --------------------------------------------------------
    # 2. Create parameter binding dictionary
    # --------------------------------------------------------

    parameter_dict = {
        theta[i]: float(parameter_values[i])
        for i in range(len(parameter_values))
    }

    # --------------------------------------------------------
    # 3. Bind parameters
    # --------------------------------------------------------

    bound_circuit = circuit.assign_parameters(
        parameter_dict,
        inplace=False
    )

    # --------------------------------------------------------
    # 4. IMPORTANT: verify all parameters are bound
    # --------------------------------------------------------

    remaining_parameters = bound_circuit.parameters

    if len(remaining_parameters) != 0:
        raise RuntimeError(
            "Parameter binding failed. "
            f"Remaining parameters: {remaining_parameters}"
        )

    # --------------------------------------------------------
    # 5. Add measurement
    # --------------------------------------------------------

    measured = bound_circuit.copy()
    measured.measure_all()

    # --------------------------------------------------------
    # 6. Transpile
    # --------------------------------------------------------

    compiled = transpile(
        measured,
        simulator,
        optimization_level=1
    )

    # --------------------------------------------------------
    # 7. Verify transpiled circuit has no parameters
    # --------------------------------------------------------

    if len(compiled.parameters) != 0:
        raise RuntimeError(
            "Transpiled circuit still contains parameters: "
            f"{compiled.parameters}"
        )

    # --------------------------------------------------------
    # 8. Run ideal Aer simulation
    # --------------------------------------------------------

    job = simulator.run(
        compiled,
        shots=shots,
        seed_simulator=seed
    )

    result = job.result()

    counts = result.get_counts()

    # --------------------------------------------------------
    # 9. q0 = 1 probability
    # --------------------------------------------------------

    p1 = 0.0

    for bitstring, count in counts.items():

        q0_bit = int(bitstring[-1])

        if q0_bit == 1:
            p1 += count / shots

    return p1

In [ ]:
# ============================================================
# SINGLE-SAMPLE IDEAL VQC TEST
# ============================================================

print("=" * 60)
print("SINGLE-SAMPLE IDEAL VQC TEST")
print("=" * 60)

test_probability = vqc_probability(
    X_test_q[0],
    theta,
    shots=SHOTS,
    seed=SEED_SIMULATOR
)

test_prediction = int(test_probability >= 0.5)

print("Sample index     : 0")
print("True label       :", y_test[0])
print("P(y=1)           :", round(test_probability, 6))
print("Prediction       :", test_prediction)

assert 0.0 <= test_probability <= 1.0

print("\nValidation: PASS")

In [ ]:
# ============================================================
# FIX: SEPARATE CIRCUIT PARAMETERS FROM TRAINED PARAMETERS
# ============================================================

from qiskit import QuantumCircuit, transpile
from qiskit.circuit import ParameterVector
from qiskit_aer import AerSimulator

# ------------------------------------------------------------
# 1. Load trained numerical parameters
# ------------------------------------------------------------

TRAINED_THETA_FILE = RESULTS_DIR / "trained_theta.npy"

trained_theta = np.load(TRAINED_THETA_FILE)

print("=" * 60)
print("TRAINED PARAMETERS")
print("=" * 60)

print("File  :", TRAINED_THETA_FILE)
print("Shape :", trained_theta.shape)
print("Count :", len(trained_theta))

assert trained_theta.shape == (16,)

# ------------------------------------------------------------
# 2. Create a NEW parameter vector ONLY for the circuit
# ------------------------------------------------------------

VQC_PARAMS = ParameterVector(
    "θ",
    length=N_PARAMS
)

# ------------------------------------------------------------
# 3. Exact VQC architecture from 05
# ------------------------------------------------------------

def build_vqc(
    feature_angles,
    n_qubits=4,
    n_layers=2
):

    qc = QuantumCircuit(n_qubits)

    # --------------------------------------------------------
    # Feature encoding
    # --------------------------------------------------------

    for qubit, angle in enumerate(feature_angles):

        qc.ry(angle, qubit)
        qc.rz(angle, qubit)

    # --------------------------------------------------------
    # Feature-map entanglement
    # --------------------------------------------------------

    for qubit in range(n_qubits - 1):

        qc.cx(
            qubit,
            qubit + 1
        )

    # --------------------------------------------------------
    # Variational layers
    # --------------------------------------------------------

    parameter_index = 0

    for layer in range(n_layers):

        for qubit in range(n_qubits):

            qc.ry(
                VQC_PARAMS[parameter_index],
                qubit
            )

            parameter_index += 1

            qc.rz(
                VQC_PARAMS[parameter_index],
                qubit
            )

            parameter_index += 1

        # ----------------------------------------------------
        # Variational entanglement
        # ----------------------------------------------------

        for qubit in range(n_qubits - 1):

            qc.cx(
                qubit,
                qubit + 1
            )

    return qc


# ------------------------------------------------------------
# 4. Ideal simulator
# ------------------------------------------------------------

simulator = AerSimulator()

# ------------------------------------------------------------
# 5. Inference function
# ------------------------------------------------------------

def vqc_probability(
    feature_angles,
    parameter_values,
    shots=1024,
    seed=42
):

    # Build circuit
    circuit = build_vqc(
        feature_angles,
        n_qubits=N_QUBITS,
        n_layers=N_LAYERS
    )

    # --------------------------------------------------------
    # Bind circuit parameters to numerical trained values
    # --------------------------------------------------------

    parameter_dict = {
        VQC_PARAMS[i]: float(parameter_values[i])
        for i in range(N_PARAMS)
    }

    bound_circuit = circuit.assign_parameters(
        parameter_dict,
        inplace=False
    )

    # --------------------------------------------------------
    # Verify parameter binding
    # --------------------------------------------------------

    if len(bound_circuit.parameters) != 0:

        raise RuntimeError(
            "Parameter binding failed.\n"
            f"Remaining parameters: {bound_circuit.parameters}"
        )

    # --------------------------------------------------------
    # Measurement
    # --------------------------------------------------------

    measured = bound_circuit.copy()

    measured.measure_all()

    # --------------------------------------------------------
    # Transpile
    # --------------------------------------------------------

    compiled = transpile(
        measured,
        simulator,
        optimization_level=1
    )

    # --------------------------------------------------------
    # Verify transpiled circuit
    # --------------------------------------------------------

    if len(compiled.parameters) != 0:

        raise RuntimeError(
            "Transpiled circuit still contains parameters.\n"
            f"Parameters: {compiled.parameters}"
        )

    # --------------------------------------------------------
    # Run ideal simulation
    # --------------------------------------------------------

    job = simulator.run(
        compiled,
        shots=shots,
        seed_simulator=seed
    )

    result = job.result()

    counts = result.get_counts()

    # --------------------------------------------------------
    # q0 = 1 probability
    # --------------------------------------------------------

    p1 = 0.0

    for bitstring, count in counts.items():

        q0_bit = int(bitstring[-1])

        if q0_bit == 1:

            p1 += count / shots

    return p1


print("\nCircuit parameters :", len(VQC_PARAMS))
print("Trained parameters :", len(trained_theta))
print("Simulator          :", simulator.name)

print("\nValidation: PASS")

In [ ]:
# ============================================================
# SINGLE-SAMPLE IDEAL VQC TEST
# ============================================================

print("=" * 60)
print("SINGLE-SAMPLE IDEAL VQC TEST")
print("=" * 60)

test_probability = vqc_probability(
    X_test_q[0],
    trained_theta,
    shots=SHOTS,
    seed=SEED_SIMULATOR
)

test_prediction = int(
    test_probability >= 0.5
)

print("Sample index     :", 0)
print("True label       :", y_test[0])
print("P(y=1)           :", round(test_probability, 6))
print("Prediction       :", test_prediction)

assert 0.0 <= test_probability <= 1.0

print("\nValidation: PASS")

In [ ]:
# ============================================================
# IDEAL VQC INFERENCE - FULL TEST SET
# ============================================================

ideal_probabilities = []
ideal_predictions = []

print("=" * 60)
print("RUNNING IDEAL VQC INFERENCE")
print("=" * 60)

print("Test samples :", len(X_test_q))
print("Shots        :", SHOTS)

for i, feature_angles in enumerate(X_test_q):

    sample_seed = SEED_SIMULATOR + i

    probability = vqc_probability(
        feature_angles,
        trained_theta,
        shots=SHOTS,
        seed=sample_seed
    )

    prediction = int(probability >= 0.5)

    ideal_probabilities.append(probability)
    ideal_predictions.append(prediction)

    if (i + 1) % 25 == 0:
        print(
            f"Processed "
            f"{i + 1:03d}/{len(X_test_q)} samples"
        )

ideal_probabilities = np.asarray(
    ideal_probabilities,
    dtype=float
)

ideal_predictions = np.asarray(
    ideal_predictions,
    dtype=int
)

print("\nInference complete.")

print("Probability shape :", ideal_probabilities.shape)
print("Prediction shape  :", ideal_predictions.shape)

assert len(ideal_probabilities) == 200
assert len(ideal_predictions) == 200

assert np.all(
    (ideal_probabilities >= 0.0) &
    (ideal_probabilities <= 1.0)
)

print("\nValidation: PASS")

In [ ]:
# ============================================================
# IDEAL VQC EVALUATION
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

ideal_accuracy = accuracy_score(
    y_test,
    ideal_predictions
)

ideal_error_rate = 1.0 - ideal_accuracy

cm = confusion_matrix(
    y_test,
    ideal_predictions
)

print("=" * 60)
print("IDEAL VQC EVALUATION")
print("=" * 60)

print("Accuracy   :", round(ideal_accuracy, 6))
print("Error Rate :", round(ideal_error_rate, 6))

print("\nConfusion Matrix:")
print(cm)

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        ideal_predictions,
        digits=6
    )
)

In [ ]:
# ============================================================
# SAVE IDEAL VQC RESULTS
# ============================================================

ideal_results = pd.DataFrame({
    "True_Label": y_test,
    "Predicted_Label": ideal_predictions,
    "Probability_Class_1": ideal_probabilities
})

ideal_results_path = RESULTS_DIR / "ideal_results.csv"

ideal_results.to_csv(
    ideal_results_path,
    index=False
)

# Save predictions separately
ideal_predictions_path = RESULTS_DIR / "ideal_predictions.npy"

np.save(
    ideal_predictions_path,
    ideal_predictions
)

# Save metrics
ideal_metrics = pd.DataFrame([{
    "experiment": "ideal_simulation",
    "simulator": simulator.name,
    "noise": "OFF",
    "test_samples": len(y_test),
    "shots": SHOTS,
    "n_qubits": N_QUBITS,
    "n_layers": N_LAYERS,
    "n_parameters": N_PARAMS,
    "accuracy": ideal_accuracy,
    "error_rate": ideal_error_rate
}])

ideal_metrics_path = RESULTS_DIR / "ideal_metrics.csv"

ideal_metrics.to_csv(
    ideal_metrics_path,
    index=False
)

print("=" * 60)
print("IDEAL RESULTS SAVED")
print("=" * 60)

print("Results :")
print(ideal_results_path)

print("\nPredictions :")
print(ideal_predictions_path)

print("\nMetrics :")
print(ideal_metrics_path)

print("\nValidation: PASS")

In [ ]:
# ============================================================
# IDEAL VQC - CONFUSION MATRIX FIGURE
# ============================================================

import matplotlib.pyplot as plt

FIGURES_DIR = RESULTS_DIR / "figures"
FIGURES_DIR.mkdir(
    parents=True,
    exist_ok=True
)

fig, ax = plt.subplots(figsize=(6, 5))

im = ax.imshow(cm)

ax.set_title("Ideal VQC Confusion Matrix")
ax.set_xlabel("Predicted Label")
ax.set_ylabel("True Label")

ax.set_xticks([0, 1])
ax.set_yticks([0, 1])

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        ax.text(
            j,
            i,
            cm[i, j],
            ha="center",
            va="center"
        )

fig.colorbar(im, ax=ax)

fig.tight_layout()

confusion_path = (
    FIGURES_DIR /
    "ideal_confusion_matrix.png"
)

fig.savefig(
    confusion_path,
    dpi=300,
    bbox_inches="tight"
)

plt.show()
plt.close(fig)

print("=" * 60)
print("CONFUSION MATRIX SAVED")
print("=" * 60)
print("File :", confusion_path)

print("\nValidation: PASS")

In [ ]:
# ============================================================
# IDEAL VQC - PROBABILITY DISTRIBUTION
# ============================================================

fig, ax = plt.subplots(figsize=(7, 5))

ax.hist(
    ideal_probabilities[y_test == 0],
    bins=20,
    alpha=0.7,
    label="True class 0"
)

ax.hist(
    ideal_probabilities[y_test == 1],
    bins=20,
    alpha=0.7,
    label="True class 1"
)

ax.set_title(
    "Ideal VQC Class-1 Probability Distribution"
)

ax.set_xlabel("P(y=1)")
ax.set_ylabel("Number of samples")

ax.legend()

fig.tight_layout()

probability_path = (
    FIGURES_DIR /
    "ideal_probability_distribution.png"
)

fig.savefig(
    probability_path,
    dpi=300,
    bbox_inches="tight"
)

plt.show()
plt.close(fig)

print("=" * 60)
print("PROBABILITY DISTRIBUTION SAVED")
print("=" * 60)
print("File :", probability_path)

print("\nValidation: PASS")

In [ ]:
# ============================================================
# CELL 1 — INITIALIZATION
# ============================================================

from pathlib import Path
import numpy as np
import pandas as pd
import qiskit
import qiskit_aer

PROJECT_ROOT = Path(r"C:\Users\heart\quantum_6g_ai")

RESULTS_DIR = PROJECT_ROOT / "results"
THETA_PATH = RESULTS_DIR / "trained_theta.npy"

print("=" * 60)
print("NOISY VQC SIMULATION — INITIALIZATION")
print("=" * 60)

print("Project root :", PROJECT_ROOT)
print("Theta path   :", THETA_PATH)
print("Qiskit       :", qiskit.__version__)
print("Qiskit Aer   :", qiskit_aer.__version__)

if not THETA_PATH.exists():
    raise FileNotFoundError(
        f"Trained parameter file not found:\n{THETA_PATH}"
    )

# Numerical trained parameters
trained_theta = np.load(THETA_PATH)

print("\nTrained parameter vector loaded")
print("Shape        :", trained_theta.shape)
print("Parameters   :", len(trained_theta))
print("Min          :", trained_theta.min())
print("Max          :", trained_theta.max())
print("Mean         :", trained_theta.mean())
print("Std          :", trained_theta.std())

assert len(trained_theta) == 16

print("\nValidation: TRAINED PARAMETERS LOADED")

In [ ]:
# ============================================================
# CELL 2 — VQC CIRCUIT RECONSTRUCTION
# ============================================================

from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector

N_QUBITS = 4
N_LAYERS = 2

theta_params = ParameterVector("theta", length=16)


def build_vqc_circuit(features, theta=theta_params, measure=False):
    """
    Reconstruct the VQC architecture used in 05_vqc_training.ipynb.

    Architecture:
        Data encoding:
            Ry(x_i)
            Rz(x_i)

        VQC layer 1:
            CNOT chain
            Ry(theta)
            Rz(theta)

        VQC layer 2:
            CNOT chain
            Ry(theta)
            Rz(theta)

    Parameters:
        features : array-like, length 4
        theta    : 16 trainable parameters
    """

    if len(features) != 4:
        raise ValueError(
            f"Expected 4 features, got {len(features)}"
        )

    qc = QuantumCircuit(N_QUBITS)

    # --------------------------------------------------------
    # DATA ENCODING
    # --------------------------------------------------------
    for q in range(N_QUBITS):
        qc.ry(float(features[q]), q)
        qc.rz(float(features[q]), q)

    # --------------------------------------------------------
    # VQC LAYER 1
    # --------------------------------------------------------
    qc.cx(0, 1)
    qc.cx(1, 2)
    qc.cx(2, 3)

    for q in range(N_QUBITS):
        qc.ry(theta[2*q], q)
        qc.rz(theta[2*q + 1], q)

    # --------------------------------------------------------
    # VQC LAYER 2
    # --------------------------------------------------------
    qc.cx(0, 1)
    qc.cx(1, 2)
    qc.cx(2, 3)

    offset = 8

    for q in range(N_QUBITS):
        qc.ry(theta[offset + 2*q], q)
        qc.rz(theta[offset + 2*q + 1], q)

    # --------------------------------------------------------
    # OPTIONAL MEASUREMENT
    # --------------------------------------------------------
    if measure:
        qc.measure_all()

    return qc


# ------------------------------------------------------------
# TEST CIRCUIT
# ------------------------------------------------------------

test_features = np.array([
    0.73731,
    -0.73731,
    -0.33427,
    1.27970
])

test_circuit = build_vqc_circuit(test_features)

print("=" * 60)
print("VQC CIRCUIT RECONSTRUCTION")
print("=" * 60)

print("Qubits       :", test_circuit.num_qubits)
print("Parameters   :", len(theta_params))
print("Depth        :", test_circuit.depth())
print("Gate counts  :", dict(test_circuit.count_ops()))

print("\nCircuit:")
print(test_circuit)

print("\nValidation: VQC CIRCUIT CREATED")

In [ ]:
# ============================================================
# CELL 2 — ORIGINAL VQC ARCHITECTURE
# ============================================================

from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector

N_QUBITS = 4
N_LAYERS = 2

# Same 16 trainable parameters used in 05_vqc_training.ipynb
theta = ParameterVector("theta", length=16)


def build_vqc(
    feature_angles,
    n_qubits=4,
    n_layers=2
):
    """
    Original VQC architecture from 05_vqc_training.ipynb.

    Part 1:
        Classical feature encoding
        Ry(x) + Rz(x)

    Part 2:
        Linear CNOT feature-map entanglement

    Part 3:
        Trainable variational layers
        Ry(theta) + Rz(theta)
        + linear CNOT entanglement
    """

    qc = QuantumCircuit(n_qubits)

    # -----------------------------------------------------
    # Feature encoding
    # -----------------------------------------------------

    for qubit, angle in enumerate(feature_angles):
        qc.ry(angle, qubit)
        qc.rz(angle, qubit)

    # -----------------------------------------------------
    # Feature-map entanglement
    # -----------------------------------------------------

    for qubit in range(n_qubits - 1):
        qc.cx(qubit, qubit + 1)

    # -----------------------------------------------------
    # Variational layers
    # -----------------------------------------------------

    parameter_index = 0

    for layer in range(n_layers):

        for qubit in range(n_qubits):

            qc.ry(
                theta[parameter_index],
                qubit
            )

            parameter_index += 1

            qc.rz(
                theta[parameter_index],
                qubit
            )

            parameter_index += 1

        # Variational entanglement
        for qubit in range(n_qubits - 1):
            qc.cx(qubit, qubit + 1)

    return qc

In [ ]:
# ============================================================
# CELL 3 — VERIFY ORIGINAL VQC ARCHITECTURE
# ============================================================

test_features = np.array([
    0.73731,
    -0.73731,
    -0.33427,
    1.27970
])

test_circuit = build_vqc(
    feature_angles=test_features,
    n_qubits=4,
    n_layers=2
)

print("=" * 60)
print("VQC ARCHITECTURE VERIFICATION")
print("=" * 60)

print("Qubits          :", test_circuit.num_qubits)
print("VQC layers      :", N_LAYERS)
print("Parameters      :", len(theta))
print("Depth           :", test_circuit.depth())
print("Gate counts     :", dict(test_circuit.count_ops()))

print("\nCircuit:")
print(test_circuit)

print("\nValidation: ORIGINAL VQC ARCHITECTURE RECONSTRUCTED")

In [ ]:
# ============================================================
# CELL 4 — BIND TRAINED PARAMETERS
# ============================================================

# IMPORTANT:
# Keep Qiskit symbolic parameters and numerical trained
# parameters under different names.

# Symbolic parameters used by the VQC circuit
vqc_parameters = theta

# Numerical parameters loaded from trained_theta.npy
trained_theta = np.asarray(theta_values, dtype=float)

In [6]:
# ============================================================
# DATASET FILE DISCOVERY
# ============================================================

from pathlib import Path

PROJECT_ROOT = Path(r"C:\Users\heart\quantum_6g_ai")
RESULTS_DIR = PROJECT_ROOT / "results"

print("=" * 60)
print("SEARCHING FOR EXISTING TEST DATA")
print("=" * 60)

print("\nFiles currently in results/:")

for path in sorted(RESULTS_DIR.iterdir()):
    print(" -", path.name)

============================================================
SEARCHING FOR EXISTING TEST DATA
============================================================

Files currently in results/:
 - 6g_trust_dataset.csv
 - figures
 - final_research_evidence_summary.csv
 - hardware_bootstrap_ci.csv
 - hardware_confusion_matrix.csv
 - hardware_full_results.csv
 - hardware_full_summary.csv
 - hardware_pilot_10_results.csv
 - hardware_pilot_10_summary.csv
 - hardware_runs.csv
 - hardware_statistical_validation.csv
 - ideal_metrics.csv
 - ideal_predictions.npy
 - ideal_results.csv
 - master_experimental_comparison.csv
 - metrics.csv
 - noise_comparison.csv
 - noise_impact.csv
 - noise_robustness_sweep.csv
 - noise_single_sample_sweep.csv
 - noisy_results.csv
 - publication_experimental_table.csv
 - quantum_encoding_config.json
 - quantum_test_features.csv
 - quantum_train_features.csv
 - test_scaled.csv
 - train_scaled.csv
 - trained_theta.npy
 - training_history.csv

In [7]:
# ============================================================
# CELL 5 — LOAD EXISTING TEST DATA
# ============================================================

import pandas as pd
import numpy as np

TEST_SCALED_PATH = RESULTS_DIR / "test_scaled.csv"
QUANTUM_TEST_PATH = RESULTS_DIR / "quantum_test_features.csv"

print("=" * 60)
print("EXISTING TEST DATA VALIDATION")
print("=" * 60)

# ------------------------------------------------------------
# Check files
# ------------------------------------------------------------

print("\nTest scaled file:")
print(TEST_SCALED_PATH)

print("\nQuantum test features file:")
print(QUANTUM_TEST_PATH)

if not TEST_SCALED_PATH.exists():
    raise FileNotFoundError(
        f"Missing:\n{TEST_SCALED_PATH}"
    )

if not QUANTUM_TEST_PATH.exists():
    raise FileNotFoundError(
        f"Missing:\n{QUANTUM_TEST_PATH}"
    )

# ------------------------------------------------------------
# Load data
# ------------------------------------------------------------

test_scaled = pd.read_csv(TEST_SCALED_PATH)
quantum_test = pd.read_csv(QUANTUM_TEST_PATH)

print("\n" + "=" * 60)
print("DATASET SHAPES")
print("=" * 60)

print("test_scaled shape :", test_scaled.shape)
print("quantum_test shape:", quantum_test.shape)

print("\n--- test_scaled columns ---")
print(test_scaled.columns.tolist())

print("\n--- quantum_test columns ---")
print(quantum_test.columns.tolist())

print("\n--- first 5 quantum test samples ---")
display(quantum_test.head())

print("\nValidation: EXISTING TEST DATA LOADED")

============================================================
EXISTING TEST DATA VALIDATION
============================================================

Test scaled file:
C:\Users\heart\quantum_6g_ai\results\test_scaled.csv

Quantum test features file:
C:\Users\heart\quantum_6g_ai\results\quantum_test_features.csv

============================================================
DATASET SHAPES
============================================================
test_scaled shape : (200, 10)
quantum_test shape: (200, 5)

--- test_scaled columns ---
['SINR', 'RSRP', 'Latency', 'Packet_Loss', 'Throughput', 'Interference', 'Resource_Load', 'Trust_Score', 'Risk_Score', 'Label']

--- quantum_test columns ---
['Trust_Score', 'Risk_Score', 'Interference', 'Resource_Load', 'Label']

--- first 5 quantum test samples ---

   Trust_Score  Risk_Score  Interference  Resource_Load  Label
0    -0.011302    0.011302     -1.801956      -0.344734      1
1     2.349209   -2.349209     -3.115075      -0.126104      0
2     2.177502   -2.177502      1.472018      -0.516761      0
3     1.857853   -1.857853     -0.097556       2.033804      0
4     1.254814   -1.254814      0.171669      -0.005007      1

Validation: EXISTING TEST DATA LOADED

In [8]:
# ============================================================
# CELL 6 — PREPARE VQC TEST SET
# ============================================================

# ------------------------------------------------------------
# VQC feature columns
# ------------------------------------------------------------

VQC_FEATURE_COLUMNS = [
    "Trust_Score",
    "Risk_Score",
    "Interference",
    "Resource_Load"
]

LABEL_COLUMN = "Label"

# ------------------------------------------------------------
# Extract features and labels
# ------------------------------------------------------------

X_test = quantum_test[VQC_FEATURE_COLUMNS].to_numpy(
    dtype=float
)

y_test = quantum_test[LABEL_COLUMN].to_numpy(
    dtype=int
)

print("=" * 60)
print("VQC TEST SET PREPARATION")
print("=" * 60)

print("X_test shape :", X_test.shape)
print("y_test shape :", y_test.shape)

print("\nFeature columns:")
for i, col in enumerate(VQC_FEATURE_COLUMNS):
    print(f"  Feature {i}: {col}")

print("\nLabel distribution:")
print(pd.Series(y_test).value_counts().sort_index())

print("\nFirst 5 feature vectors:")
print(X_test[:5])

print("\nFirst 5 labels:")
print(y_test[:5])

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert X_test.shape == (200, 4)
assert y_test.shape == (200,)
assert np.all(np.isfinite(X_test))
assert set(np.unique(y_test)).issubset({0, 1})

print("\nValidation: VQC TEST SET READY")

============================================================
VQC TEST SET PREPARATION
============================================================
X_test shape : (200, 4)
y_test shape : (200,)

Feature columns:
  Feature 0: Trust_Score
  Feature 1: Risk_Score
  Feature 2: Interference
  Feature 3: Resource_Load

Label distribution:
0    100
1    100
Name: count, dtype: int64

First 5 feature vectors:
[[-0.01130174  0.01130174 -1.80195572 -0.34473423]
 [ 2.34920917 -2.34920917 -3.11507527 -0.12610351]
 [ 2.17750211 -2.17750211  1.47201795 -0.51676068]
 [ 1.85785319 -1.85785319 -0.09755635  2.0338042 ]
 [ 1.25481401 -1.25481401  0.17166937 -0.00500675]]

First 5 labels:
[1 0 0 0 1]

Validation: VQC TEST SET READY

In [9]:

# ============================================================
# E0 — IDEAL VQC PREDICTION
# ============================================================

from qiskit import transpile
from qiskit_aer import AerSimulator

simulator = AerSimulator()

E0_SHOTS = 1024
E0_SEED = 42

def vqc_probability_e0(
    feature_angles,
    parameter_values,
    shots=1024,
    seed=42
):
    """
    Exact reproduction of the original VQC prediction logic
    from 05_vqc_training.ipynb.

    Returns:
        P(y=1)
    """

    # --------------------------------------------------------
    # Build original VQC
    # --------------------------------------------------------

    circuit = build_vqc(
        feature_angles,
        n_qubits=N_QUBITS,
        n_layers=N_LAYERS
    )

    # --------------------------------------------------------
    # Bind trained numerical parameters
    # --------------------------------------------------------

    parameter_dict = {
        vqc_parameters[i]: float(parameter_values[i])
        for i in range(len(parameter_values))
    }

    circuit = circuit.assign_parameters(
        parameter_dict
    )

    # --------------------------------------------------------
    # Measurement
    # --------------------------------------------------------

    circuit.measure_all()

    # --------------------------------------------------------
    # Transpile
    # --------------------------------------------------------

    compiled = transpile(
        circuit,
        simulator,
        optimization_level=1
    )

    # --------------------------------------------------------
    # Execute
    # --------------------------------------------------------

    job = simulator.run(
        compiled,
        shots=shots,
        seed_simulator=seed
    )

    result = job.result()
    counts = result.get_counts()

    # --------------------------------------------------------
    # Original q0 probability logic
    # --------------------------------------------------------

    p1 = 0.0

    for bitstring, count in counts.items():

        q0_bit = int(bitstring[-1])

        if q0_bit == 1:
            p1 += count / shots

    return p1

In [11]:
# ============================================================
# LOAD TRAINED VQC PARAMETERS
# ============================================================

from pathlib import Path
import numpy as np

PROJECT_ROOT = Path(r"C:\Users\heart\quantum_6g_ai")
RESULTS_DIR = PROJECT_ROOT / "results"

THETA_PATH = RESULTS_DIR / "trained_theta.npy"

if not THETA_PATH.exists():
    raise FileNotFoundError(
        f"Trained parameter file not found:\n{THETA_PATH}"
    )

trained_theta = np.load(THETA_PATH)

print("=" * 60)
print("TRAINED VQC PARAMETERS")
print("=" * 60)

print("Path         :", THETA_PATH)
print("Shape        :", trained_theta.shape)
print("Parameters   :", len(trained_theta))
print("Min          :", trained_theta.min())
print("Max          :", trained_theta.max())
print("Mean         :", trained_theta.mean())
print("Std          :", trained_theta.std())

assert trained_theta.shape == (16,)

print("\nValidation: TRAINED PARAMETERS LOADED")

============================================================
TRAINED VQC PARAMETERS
============================================================
Path         : C:\Users\heart\quantum_6g_ai\results\trained_theta.npy
Shape        : (16,)
Parameters   : 16
Min          : -0.712961678257322
Max          : 3.076039906062166
Mean         : 0.1772978436178986
Std          : 0.8534418022550907

Validation: TRAINED PARAMETERS LOADED

In [12]:
# ============================================================
# LOAD TRAINED VQC PARAMETERS
# ============================================================

from pathlib import Path
import numpy as np

PROJECT_ROOT = Path(r"C:\Users\heart\quantum_6g_ai")
RESULTS_DIR = PROJECT_ROOT / "results"

THETA_PATH = RESULTS_DIR / "trained_theta.npy"

if not THETA_PATH.exists():
    raise FileNotFoundError(
        f"Trained parameter file not found:\n{THETA_PATH}"
    )

trained_theta = np.load(THETA_PATH)

print("=" * 60)
print("TRAINED VQC PARAMETERS")
print("=" * 60)

print("Path         :", THETA_PATH)
print("Shape        :", trained_theta.shape)
print("Parameters   :", len(trained_theta))
print("Min          :", trained_theta.min())
print("Max          :", trained_theta.max())
print("Mean         :", trained_theta.mean())
print("Std          :", trained_theta.std())

assert trained_theta.shape == (16,)

print("\nValidation: TRAINED PARAMETERS LOADED")

============================================================
TRAINED VQC PARAMETERS
============================================================
Path         : C:\Users\heart\quantum_6g_ai\results\trained_theta.npy
Shape        : (16,)
Parameters   : 16
Min          : -0.712961678257322
Max          : 3.076039906062166
Mean         : 0.1772978436178986
Std          : 0.8534418022550907

Validation: TRAINED PARAMETERS LOADED

In [13]:
# ============================================================
# E0 — SINGLE SAMPLE VALIDATION
# ============================================================

test_sample_index = 0

sample_angles = X_test[test_sample_index]

p1 = vqc_probability_e0(
    sample_angles,
    trained_theta,
    shots=E0_SHOTS,
    seed=E0_SEED
)

print("=" * 60)
print("E0 SINGLE SAMPLE VALIDATION")
print("=" * 60)

print("Sample index :", test_sample_index)
print("Features     :", sample_angles)
print("True label   :", y_test[test_sample_index])
print("P(y=1)       :", round(p1, 6))
print("Prediction   :", int(p1 >= 0.5))

NameError: name 'build_vqc' is not defined

In [14]:
# ============================================================
# E0 — VQC ARCHITECTURE SETUP
# ============================================================

from qiskit import QuantumCircuit
from qiskit.circuit import ParameterVector

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

N_QUBITS = 4
N_LAYERS = 2

vqc_parameters = ParameterVector(
    "theta",
    length=16
)

# ------------------------------------------------------------
# Original VQC architecture
# ------------------------------------------------------------

def build_vqc(
    feature_angles,
    n_qubits=4,
    n_layers=2
):
    """
    Exact VQC architecture used during original training.

    Feature encoding:
        Ry(x) + Rz(x)

    Feature entanglement:
        Linear CNOT chain

    Variational layers:
        Ry(theta) + Rz(theta)
        Linear CNOT chain
    """

    qc = QuantumCircuit(n_qubits)

    # --------------------------------------------------------
    # Feature encoding
    # --------------------------------------------------------

    for qubit, angle in enumerate(feature_angles):

        qc.ry(
            angle,
            qubit
        )

        qc.rz(
            angle,
            qubit
        )

    # --------------------------------------------------------
    # Feature-map entanglement
    # --------------------------------------------------------

    for qubit in range(n_qubits - 1):

        qc.cx(
            qubit,
            qubit + 1
        )

    # --------------------------------------------------------
    # Variational layers
    # --------------------------------------------------------

    parameter_index = 0

    for layer in range(n_layers):

        for qubit in range(n_qubits):

            qc.ry(
                vqc_parameters[parameter_index],
                qubit
            )

            parameter_index += 1

            qc.rz(
                vqc_parameters[parameter_index],
                qubit
            )

            parameter_index += 1

        # Variational entanglement

        for qubit in range(n_qubits - 1):

            qc.cx(
                qubit,
                qubit + 1
            )

    return qc


# ------------------------------------------------------------
# Architecture verification
# ------------------------------------------------------------

verification_circuit = build_vqc(
    X_test[0],
    n_qubits=N_QUBITS,
    n_layers=N_LAYERS
)

print("=" * 60)
print("E0 VQC ARCHITECTURE SETUP")
print("=" * 60)

print("Qubits          :", N_QUBITS)
print("VQC layers      :", N_LAYERS)
print("Parameters      :", len(vqc_parameters))
print("Depth           :", verification_circuit.depth())
print("Gate counts     :", dict(verification_circuit.count_ops()))
print("Unbound params  :", len(verification_circuit.parameters))

assert len(vqc_parameters) == 16
assert verification_circuit.depth() == 13
assert verification_circuit.count_ops().get("ry", 0) == 12
assert verification_circuit.count_ops().get("rz", 0) == 12
assert verification_circuit.count_ops().get("cx", 0) == 9

print("\nValidation: ORIGINAL VQC ARCHITECTURE READY")

============================================================
E0 VQC ARCHITECTURE SETUP
============================================================
Qubits          : 4
VQC layers      : 2
Parameters      : 16
Depth           : 13
Gate counts     : {'ry': 12, 'rz': 12, 'cx': 9}
Unbound params  : 16

Validation: ORIGINAL VQC ARCHITECTURE READY

In [15]:
# ============================================================
# E0 — SINGLE SAMPLE VALIDATION
# ============================================================

test_sample_index = 0

sample_angles = X_test[test_sample_index]

p1 = vqc_probability_e0(
    sample_angles,
    trained_theta,
    shots=E0_SHOTS,
    seed=E0_SEED
)

print("=" * 60)
print("E0 SINGLE SAMPLE VALIDATION")
print("=" * 60)

print("Sample index :", test_sample_index)
print("Features     :", sample_angles)
print("True label   :", y_test[test_sample_index])
print("P(y=1)       :", round(p1, 6))
print("Prediction   :", int(p1 >= 0.5))

============================================================
E0 SINGLE SAMPLE VALIDATION
============================================================
Sample index : 0
Features     : [-0.01130174  0.01130174 -1.80195572 -0.34473423]
True label   : 1
P(y=1)       : 0.995117
Prediction   : 1

In [16]:
# ============================================================
# E0 — FULL IDEAL VQC EVALUATION
# ============================================================

def vqc_predict_proba_e0(
    X_data,
    parameter_values,
    shots=1024,
    seed=42
):
    """
    Generate P(y=1) for every sample.

    Uses the exact prediction logic from
    05_vqc_training.ipynb.
    """

    probabilities = []

    for i, feature_angles in enumerate(X_data):

        sample_seed = seed + i

        p1 = vqc_probability_e0(
            feature_angles,
            parameter_values,
            shots=shots,
            seed=sample_seed
        )

        probabilities.append(p1)

    return np.asarray(probabilities)


print("=" * 60)
print("E0 IDEAL VQC EVALUATION")
print("=" * 60)

ideal_probabilities = vqc_predict_proba_e0(
    X_test,
    trained_theta,
    shots=E0_SHOTS,
    seed=E0_SEED
)

ideal_predictions = (
    ideal_probabilities >= 0.5
).astype(int)

print("Samples       :", len(X_test))
print("Shots         :", E0_SHOTS)
print("Base seed     :", E0_SEED)

print("\nProbability statistics:")
print("Min           :", round(ideal_probabilities.min(), 6))
print("Max           :", round(ideal_probabilities.max(), 6))
print("Mean          :", round(ideal_probabilities.mean(), 6))
print("Std           :", round(ideal_probabilities.std(), 6))

print("\nPrediction distribution:")
print(
    pd.Series(
        ideal_predictions
    ).value_counts().sort_index()
)

assert len(ideal_probabilities) == 200
assert len(ideal_predictions) == 200

print("\nValidation: E0 IDEAL PREDICTIONS GENERATED")

============================================================
E0 IDEAL VQC EVALUATION
============================================================
Samples       : 200
Shots         : 1024
Base seed     : 42

Probability statistics:
Min           : 0.00293
Max           : 0.998047
Mean          : 0.527642
Std           : 0.344554

Prediction distribution:
0     96
1    104
Name: count, dtype: int64

Validation: E0 IDEAL PREDICTIONS GENERATED

In [17]:
# ============================================================
# E0 — IDEAL VQC METRICS
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

ideal_accuracy = accuracy_score(
    y_test,
    ideal_predictions
)

ideal_precision = precision_score(
    y_test,
    ideal_predictions,
    zero_division=0
)

ideal_recall = recall_score(
    y_test,
    ideal_predictions,
    zero_division=0
)

ideal_f1 = f1_score(
    y_test,
    ideal_predictions,
    zero_division=0
)

ideal_cm = confusion_matrix(
    y_test,
    ideal_predictions
)

print("=" * 60)
print("E0 IDEAL VQC RESULTS")
print("=" * 60)

print("Accuracy  :", round(ideal_accuracy, 6))
print("Precision :", round(ideal_precision, 6))
print("Recall    :", round(ideal_recall, 6))
print("F1 Score  :", round(ideal_f1, 6))

print("\nConfusion Matrix:")
print(ideal_cm)

print("\nValidation: E0 IDEAL BASELINE COMPLETE")

============================================================
E0 IDEAL VQC RESULTS
============================================================
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1 Score  : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

Validation: E0 IDEAL BASELINE COMPLETE

In [18]:
# ============================================================
# E0 — SAVE FROZEN BASELINE
# ============================================================

ideal_results = pd.DataFrame({
    "sample_index": np.arange(len(y_test)),
    "y_true": y_test,
    "probability_y1": ideal_probabilities,
    "prediction": ideal_predictions
})

ideal_results_path = RESULTS_DIR / "ideal_results.csv"

ideal_results.to_csv(
    ideal_results_path,
    index=False
)

np.save(
    RESULTS_DIR / "ideal_predictions.npy",
    ideal_predictions
)

ideal_metrics = pd.DataFrame([{
    "experiment_id": "E0",
    "environment": "ideal_simulation",
    "backend": "AerSimulator",
    "noise_type": "none",
    "noise_level": 0.0,
    "shots": E0_SHOTS,
    "seed": E0_SEED,
    "n_samples": len(y_test),
    "n_qubits": N_QUBITS,
    "vqc_layers": N_LAYERS,
    "n_parameters": len(trained_theta),
    "accuracy": ideal_accuracy,
    "precision": ideal_precision,
    "recall": ideal_recall,
    "f1": ideal_f1
}])

ideal_metrics_path = RESULTS_DIR / "ideal_metrics.csv"

ideal_metrics.to_csv(
    ideal_metrics_path,
    index=False
)

print("=" * 60)
print("E0 BASELINE FROZEN")
print("=" * 60)

print("Accuracy  :", ideal_accuracy)
print("Precision :", ideal_precision)
print("Recall    :", ideal_recall)
print("F1        :", ideal_f1)

print("\nSaved:")
print(ideal_results_path)
print(RESULTS_DIR / "ideal_predictions.npy")
print(ideal_metrics_path)

print("\nValidation: E0 BASELINE SAVED")

============================================================
E0 BASELINE FROZEN
============================================================
Accuracy  : 0.85
Precision : 0.8365384615384616
Recall    : 0.87
F1        : 0.8529411764705882

Saved:
C:\Users\heart\quantum_6g_ai\results\ideal_results.csv
C:\Users\heart\quantum_6g_ai\results\ideal_predictions.npy
C:\Users\heart\quantum_6g_ai\results\ideal_metrics.csv

Validation: E0 BASELINE SAVED

In [19]:
# ============================================================
# E1.1 — CONTROLLED DEPOLARIZING NOISE MODEL
# ============================================================

from qiskit_aer import AerSimulator
from qiskit_aer.noise import NoiseModel, depolarizing_error

# ------------------------------------------------------------
# E1 experiment configuration
# ------------------------------------------------------------

E1_SHOTS = 1024
E1_SEED = 42

# Controlled depolarizing-noise sweep
E1_NOISE_LEVELS = [
    0.001,
    0.005,
    0.010,
    0.020,
    0.050
]

# ------------------------------------------------------------
# Build depolarizing noise model
# ------------------------------------------------------------

def build_e1_depolarizing_noise(noise_level):
    """
    Build a controlled depolarizing noise model.

    The same noise level is applied to:
      - 1-qubit gates: ry, rz
      - 2-qubit gates: cx

    Parameters
    ----------
    noise_level : float
        Depolarizing probability.

    Returns
    -------
    NoiseModel
        Qiskit Aer noise model.
    """

    if not 0.0 <= noise_level <= 1.0:
        raise ValueError(
            f"noise_level must be between 0 and 1, got {noise_level}"
        )

    noise_model = NoiseModel()

    # --------------------------------------------------------
    # 1-qubit depolarizing error
    # --------------------------------------------------------

    error_1q = depolarizing_error(
        noise_level,
        1
    )

    noise_model.add_all_qubit_quantum_error(
        error_1q,
        ["ry", "rz"]
    )

    # --------------------------------------------------------
    # 2-qubit depolarizing error
    # --------------------------------------------------------

    error_2q = depolarizing_error(
        noise_level,
        2
    )

    noise_model.add_all_qubit_quantum_error(
        error_2q,
        ["cx"]
    )

    return noise_model


print("=" * 60)
print("E1 DEPOLARIZING NOISE MODEL")
print("=" * 60)

print("Shots       :", E1_SHOTS)
print("Base seed   :", E1_SEED)
print("Noise levels:", E1_NOISE_LEVELS)

# ------------------------------------------------------------
# Build and inspect all noise models
# ------------------------------------------------------------

e1_noise_models = {}

for level in E1_NOISE_LEVELS:
    model = build_e1_depolarizing_noise(level)
    e1_noise_models[level] = model

    print("\nNoise level:", level)
    print(model)

print("\nValidation: E1 NOISE MODELS CREATED")

============================================================
E1 DEPOLARIZING NOISE MODEL
============================================================
Shots       : 1024
Base seed   : 42
Noise levels: [0.001, 0.005, 0.01, 0.02, 0.05]

Noise level: 0.001
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx']

Noise level: 0.005
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx']

Noise level: 0.01
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx']

Noise level: 0.02
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx']

Noise level: 0.05
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx']

Validation: E1 NOISE MODELS CREATED

In [20]:
# ============================================================
# E1.2 — SINGLE-SAMPLE DEPOLARIZING NOISE SANITY CHECK
# ============================================================

def vqc_probability_e1(
    feature_angles,
    parameter_values,
    noise_level,
    shots=1024,
    seed=42
):
    """
    Run the frozen VQC under controlled depolarizing noise.
    """

    circuit = build_vqc(
        feature_angles,
        n_qubits=N_QUBITS,
        n_layers=N_LAYERS
    )

    # Bind frozen trained parameters
    parameter_dict = {
        vqc_parameters[i]: float(parameter_values[i])
        for i in range(len(parameter_values))
    }

    circuit = circuit.assign_parameters(parameter_dict)

    circuit.measure_all()

    # --------------------------------------------------------
    # Noise model
    # --------------------------------------------------------

    noise_model = build_e1_depolarizing_noise(
        noise_level
    )

    # --------------------------------------------------------
    # Simulator
    # --------------------------------------------------------

    noisy_simulator = AerSimulator(
        noise_model=noise_model
    )

    compiled = transpile(
        circuit,
        noisy_simulator,
        optimization_level=1
    )

    job = noisy_simulator.run(
        compiled,
        shots=shots,
        seed_simulator=seed
    )

    result = job.result()
    counts = result.get_counts()

    # --------------------------------------------------------
    # P(q0 = 1)
    # --------------------------------------------------------

    p1 = 0.0

    for bitstring, count in counts.items():

        q0_bit = int(bitstring[-1])

        if q0_bit == 1:
            p1 += count / shots

    return p1


# ------------------------------------------------------------
# Test sample 0
# ------------------------------------------------------------

sample_index = 0

feature_angles = X_test[sample_index]
true_label = y_test[sample_index]

print("=" * 60)
print("E1 SINGLE-SAMPLE SANITY CHECK")
print("=" * 60)

print("Sample index :", sample_index)
print("True label   :", true_label)
print("Shots        :", E1_SHOTS)

print("\nResults:")

for level in E1_NOISE_LEVELS:

    probability = vqc_probability_e1(
        feature_angles,
        trained_theta,
        noise_level=level,
        shots=E1_SHOTS,
        seed=E1_SEED
    )

    prediction = int(probability >= 0.5)

    print(
        f"Noise={level:0.3f} | "
        f"P(y=1)={probability:.6f} | "
        f"Prediction={prediction}"
    )

print("\nValidation: E1 SINGLE-SAMPLE CHECK COMPLETE")

============================================================
E1 SINGLE-SAMPLE SANITY CHECK
============================================================
Sample index : 0
True label   : 1
Shots        : 1024

Results:
Noise=0.001 | P(y=1)=0.989258 | Prediction=1
Noise=0.005 | P(y=1)=0.967773 | Prediction=1
Noise=0.010 | P(y=1)=0.951172 | Prediction=1
Noise=0.020 | P(y=1)=0.912109 | Prediction=1
Noise=0.050 | P(y=1)=0.806641 | Prediction=1

Validation: E1 SINGLE-SAMPLE CHECK COMPLETE

In [21]:
# ============================================================
# E1.3 — FULL DEPOLARIZING NOISE SWEEP
# ============================================================

def vqc_predict_proba_e1(
    X_data,
    parameter_values,
    noise_level,
    shots=1024,
    seed=42
):
    """
    Generate VQC probabilities under controlled
    depolarizing noise.
    """

    probabilities = []

    for i, feature_angles in enumerate(X_data):

        sample_seed = seed + i

        p1 = vqc_probability_e1(
            feature_angles,
            parameter_values,
            noise_level=noise_level,
            shots=shots,
            seed=sample_seed
        )

        probabilities.append(p1)

    return np.asarray(probabilities)


# ------------------------------------------------------------
# Full E1 experiment
# ------------------------------------------------------------

e1_results = []

print("=" * 60)
print("E1 FULL DEPOLARIZING NOISE EXPERIMENT")
print("=" * 60)

print("Samples       :", len(X_test))
print("Shots         :", E1_SHOTS)
print("Base seed     :", E1_SEED)
print("Noise levels  :", E1_NOISE_LEVELS)

for noise_level in E1_NOISE_LEVELS:

    print("\n" + "-" * 60)
    print(f"Running noise level = {noise_level:.3f}")
    print("-" * 60)

    probabilities = vqc_predict_proba_e1(
        X_test,
        trained_theta,
        noise_level=noise_level,
        shots=E1_SHOTS,
        seed=E1_SEED
    )

    predictions = (probabilities >= 0.5).astype(int)

    accuracy = accuracy_score(
        y_test,
        predictions
    )

    precision = precision_score(
        y_test,
        predictions,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        predictions,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        predictions,
        zero_division=0
    )

    cm = confusion_matrix(
        y_test,
        predictions
    )

    print("Accuracy  :", round(accuracy, 6))
    print("Precision :", round(precision, 6))
    print("Recall    :", round(recall, 6))
    print("F1        :", round(f1, 6))

    print("\nConfusion Matrix:")
    print(cm)

    e1_results.append({
        "experiment_id": "E1",
        "environment": "controlled_noisy_simulation",
        "backend": "AerSimulator",
        "noise_type": "depolarizing",
        "noise_level": noise_level,
        "seed": E1_SEED,
        "shots": E1_SHOTS,
        "n_samples": len(X_test),
        "n_qubits": N_QUBITS,
        "vqc_layers": N_LAYERS,
        "n_parameters": len(trained_theta),
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    })

print("\n" + "=" * 60)
print("E1 FULL SWEEP COMPLETE")
print("=" * 60)

============================================================
E1 FULL DEPOLARIZING NOISE EXPERIMENT
============================================================
Samples       : 200
Shots         : 1024
Base seed     : 42
Noise levels  : [0.001, 0.005, 0.01, 0.02, 0.05]

------------------------------------------------------------
Running noise level = 0.001
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.005
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.010
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.020
------------------------------------------------------------
Accuracy  : 0.84
Precision : 0.820755
Recall    : 0.87
F1        : 0.84466

Confusion Matrix:
[[81 19]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.050
------------------------------------------------------------
Accuracy  : 0.845
Precision : 0.828571
Recall    : 0.87
F1        : 0.84878

Confusion Matrix:
[[82 18]
 [13 87]]

============================================================
E1 FULL SWEEP COMPLETE
============================================================

In [22]:
 # ============================================================
# E1.4 — E1 RESULT TABLE
# ============================================================

e1_metrics = pd.DataFrame(e1_results)

print("=" * 60)
print("E1 DEPOLARIZING NOISE RESULTS")
print("=" * 60)

display(
    e1_metrics[
        [
            "noise_level",
            "accuracy",
            "precision",
            "recall",
            "f1"
        ]
    ]
)

print("\nValidation: E1 RESULTS GENERATED")

============================================================
E1 DEPOLARIZING NOISE RESULTS
============================================================

   noise_level  accuracy  precision  recall        f1
0        0.001     0.850   0.836538    0.87  0.852941
1        0.005     0.850   0.836538    0.87  0.852941
2        0.010     0.850   0.836538    0.87  0.852941
3        0.020     0.840   0.820755    0.87  0.844660
4        0.050     0.845   0.828571    0.87  0.848780

Validation: E1 RESULTS GENERATED

In [23]:
# ============================================================
# E1 — SAVE FROZEN DEPOLARIZING RESULTS
# ============================================================

e1_metrics_path = RESULTS_DIR / "e1_depolarizing_metrics.csv"

e1_metrics.to_csv(
    e1_metrics_path,
    index=False
)

# ------------------------------------------------------------
# E1 vs E0 performance gaps
# ------------------------------------------------------------

e1_comparison = e1_metrics.copy()

e1_comparison["accuracy_gap"] = (
    ideal_accuracy - e1_comparison["accuracy"]
)

e1_comparison["f1_gap"] = (
    ideal_f1 - e1_comparison["f1"]
)

e1_comparison["accuracy_relative_gap"] = (
    abs(ideal_accuracy - e1_comparison["accuracy"])
    / ideal_accuracy
)

e1_comparison["f1_relative_gap"] = (
    abs(ideal_f1 - e1_comparison["f1"])
    / ideal_f1
)

e1_comparison_path = RESULTS_DIR / "e1_depolarizing_comparison.csv"

e1_comparison.to_csv(
    e1_comparison_path,
    index=False
)

print("=" * 60)
print("E1 BASELINE FROZEN")
print("=" * 60)

print("\nSaved:")
print(e1_metrics_path)
print(e1_comparison_path)

print("\nE1 vs E0:")
display(
    e1_comparison[
        [
            "noise_level",
            "accuracy",
            "f1",
            "accuracy_gap",
            "f1_gap",
            "accuracy_relative_gap",
            "f1_relative_gap"
        ]
    ]
)

print("\nValidation: E1 DEPOLARIZING RESULTS SAVED")

============================================================
E1 BASELINE FROZEN
============================================================

Saved:
C:\Users\heart\quantum_6g_ai\results\e1_depolarizing_metrics.csv
C:\Users\heart\quantum_6g_ai\results\e1_depolarizing_comparison.csv

E1 vs E0:

,noise_level,accuracy,f1,accuracy_gap,f1_gap,accuracy_relative_gap,f1_relative_gap
0,0.001,0.850,0.852941,0.000,0.000000,0.000000,0.000000
1,0.005,0.850,0.852941,0.000,0.000000,0.000000,0.000000
2,0.010,0.850,0.852941,0.000,0.000000,0.000000,0.000000
3,0.020,0.840,0.844660,0.010,0.008281,0.011765,0.009709
4,0.050,0.845,0.848780,0.005,0.004161,0.005882,0.004878

Validation: E1 DEPOLARIZING RESULTS SAVED

In [24]:
# ============================================================
# E2.1 — CONTROLLED PAULI NOISE MODEL
# ============================================================

from qiskit_aer.noise import NoiseModel, pauli_error


E2_SHOTS = 1024
E2_SEED = 42

E2_NOISE_LEVELS = [
    0.001,
    0.005,
    0.010,
    0.020,
    0.050
]


def build_e2_pauli_noise(noise_level):
    """
    Build a controlled Pauli noise model.

    The same Pauli error probability is applied to
    the actual gates used by the VQC:

        1-qubit: ry, rz
        2-qubit: cx
    """

    if not 0.0 <= noise_level <= 1.0:
        raise ValueError(
            f"noise_level must be between 0 and 1, got {noise_level}"
        )

    noise_model = NoiseModel()

    # --------------------------------------------------------
    # 1-qubit Pauli error
    #
    # I  : 1 - p
    # X/Y/Z : p/3 each
    # --------------------------------------------------------

    error_1q = pauli_error([
        ("I", 1.0 - noise_level),
        ("X", noise_level / 3.0),
        ("Y", noise_level / 3.0),
        ("Z", noise_level / 3.0)
    ])

    noise_model.add_all_qubit_quantum_error(
        error_1q,
        ["ry", "rz"]
    )

    # --------------------------------------------------------
    # 2-qubit Pauli error
    #
    # Identity + all non-identity two-qubit Pauli products
    # --------------------------------------------------------

    non_identity_2q = [
        "IX", "IY", "IZ",
        "XI", "XX", "XY", "XZ",
        "YI", "YX", "YY", "YZ",
        "ZI", "ZX", "ZY", "ZZ"
    ]

    error_probability = noise_level / len(non_identity_2q)

    error_2q = [
        ("II", 1.0 - noise_level)
    ]

    for pauli_string in non_identity_2q:
        error_2q.append(
            (pauli_string, error_probability)
        )

    error_2q = pauli_error(error_2q)

    noise_model.add_all_qubit_quantum_error(
        error_2q,
        ["cx"]
    )

    return noise_model


print("=" * 60)
print("E2 PAULI NOISE MODEL")
print("=" * 60)

print("Shots        :", E2_SHOTS)
print("Base seed    :", E2_SEED)
print("Noise levels :", E2_NOISE_LEVELS)

e2_noise_models = {}

for level in E2_NOISE_LEVELS:

    model = build_e2_pauli_noise(level)

    e2_noise_models[level] = model

    print("\nNoise level:", level)
    print(model)

print("\nValidation: E2 NOISE MODELS CREATED")

============================================================
E2 PAULI NOISE MODEL
============================================================
Shots        : 1024
Base seed    : 42
Noise levels : [0.001, 0.005, 0.01, 0.02, 0.05]

Noise level: 0.001
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx']

Noise level: 0.005
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx']

Noise level: 0.01
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx']

Noise level: 0.02
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx']

Noise level: 0.05
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx']

Validation: E2 NOISE MODELS CREATED

In [25]:
# ============================================================
# E2.2 — SINGLE-SAMPLE PAULI NOISE SANITY CHECK
# ============================================================

def vqc_probability_e2(
    feature_angles,
    parameter_values,
    noise_level,
    shots=1024,
    seed=42
):
    """
    Run frozen VQC under controlled Pauli noise.
    """

    circuit = build_vqc(
        feature_angles,
        n_qubits=N_QUBITS,
        n_layers=N_LAYERS
    )

    parameter_dict = {
        vqc_parameters[i]: float(parameter_values[i])
        for i in range(len(parameter_values))
    }

    circuit = circuit.assign_parameters(
        parameter_dict
    )

    circuit.measure_all()

    noise_model = build_e2_pauli_noise(
        noise_level
    )

    noisy_simulator = AerSimulator(
        noise_model=noise_model
    )

    compiled = transpile(
        circuit,
        noisy_simulator,
        optimization_level=1
    )

    job = noisy_simulator.run(
        compiled,
        shots=shots,
        seed_simulator=seed
    )

    result = job.result()
    counts = result.get_counts()

    p1 = 0.0

    for bitstring, count in counts.items():

        q0_bit = int(bitstring[-1])

        if q0_bit == 1:
            p1 += count / shots

    return p1


# ------------------------------------------------------------
# Test sample 0
# ------------------------------------------------------------

sample_index = 0

feature_angles = X_test[sample_index]
true_label = y_test[sample_index]

print("=" * 60)
print("E2 SINGLE-SAMPLE SANITY CHECK")
print("=" * 60)

print("Sample index :", sample_index)
print("True label   :", true_label)
print("Shots        :", E2_SHOTS)

print("\nResults:")

for level in E2_NOISE_LEVELS:

    probability = vqc_probability_e2(
        feature_angles,
        trained_theta,
        noise_level=level,
        shots=E2_SHOTS,
        seed=E2_SEED
    )

    prediction = int(
        probability >= 0.5
    )

    print(
        f"Noise={level:0.3f} | "
        f"P(y=1)={probability:.6f} | "
        f"Prediction={prediction}"
    )

print("\nValidation: E2 SINGLE-SAMPLE CHECK COMPLETE")

============================================================
E2 SINGLE-SAMPLE SANITY CHECK
============================================================
Sample index : 0
True label   : 1
Shots        : 1024

Results:
Noise=0.001 | P(y=1)=0.988281 | Prediction=1
Noise=0.005 | P(y=1)=0.968750 | Prediction=1
Noise=0.010 | P(y=1)=0.931641 | Prediction=1
Noise=0.020 | P(y=1)=0.901367 | Prediction=1
Noise=0.050 | P(y=1)=0.780273 | Prediction=1

Validation: E2 SINGLE-SAMPLE CHECK COMPLETE

In [26]:
# ============================================================
# E2.3 — FULL PAULI NOISE SWEEP
# ============================================================

def vqc_predict_proba_e2(
    X_data,
    parameter_values,
    noise_level,
    shots=1024,
    seed=42
):
    """
    Generate VQC probabilities under controlled Pauli noise.
    """

    probabilities = []

    for i, feature_angles in enumerate(X_data):

        sample_seed = seed + i

        p1 = vqc_probability_e2(
            feature_angles,
            parameter_values,
            noise_level=noise_level,
            shots=shots,
            seed=sample_seed
        )

        probabilities.append(p1)

    return np.asarray(probabilities)


# ------------------------------------------------------------
# Full E2 experiment
# ------------------------------------------------------------

e2_results = []

print("=" * 60)
print("E2 FULL PAULI NOISE EXPERIMENT")
print("=" * 60)

print("Samples       :", len(X_test))
print("Shots         :", E2_SHOTS)
print("Base seed     :", E2_SEED)
print("Noise levels  :", E2_NOISE_LEVELS)

for noise_level in E2_NOISE_LEVELS:

    print("\n" + "-" * 60)
    print(f"Running noise level = {noise_level:.3f}")
    print("-" * 60)

    probabilities = vqc_predict_proba_e2(
        X_test,
        trained_theta,
        noise_level=noise_level,
        shots=E2_SHOTS,
        seed=E2_SEED
    )

    predictions = (
        probabilities >= 0.5
    ).astype(int)

    accuracy = accuracy_score(
        y_test,
        predictions
    )

    precision = precision_score(
        y_test,
        predictions,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        predictions,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        predictions,
        zero_division=0
    )

    cm = confusion_matrix(
        y_test,
        predictions
    )

    print("Accuracy  :", round(accuracy, 6))
    print("Precision :", round(precision, 6))
    print("Recall    :", round(recall, 6))
    print("F1        :", round(f1, 6))

    print("\nConfusion Matrix:")
    print(cm)

    e2_results.append({
        "experiment_id": "E2",
        "environment": "controlled_noisy_simulation",
        "backend": "AerSimulator",
        "noise_type": "pauli",
        "noise_level": noise_level,
        "seed": E2_SEED,
        "shots": E2_SHOTS,
        "n_samples": len(X_test),
        "n_qubits": N_QUBITS,
        "vqc_layers": N_LAYERS,
        "n_parameters": len(trained_theta),
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    })


print("\n" + "=" * 60)
print("E2 FULL SWEEP COMPLETE")
print("=" * 60)

============================================================
E2 FULL PAULI NOISE EXPERIMENT
============================================================
Samples       : 200
Shots         : 1024
Base seed     : 42
Noise levels  : [0.001, 0.005, 0.01, 0.02, 0.05]

------------------------------------------------------------
Running noise level = 0.001
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.005
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.010
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.020
------------------------------------------------------------
Accuracy  : 0.835
Precision : 0.813084
Recall    : 0.87
F1        : 0.84058

Confusion Matrix:
[[80 20]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.050
------------------------------------------------------------
Accuracy  : 0.835
Precision : 0.819048
Recall    : 0.86
F1        : 0.839024

Confusion Matrix:
[[81 19]
 [14 86]]

============================================================
E2 FULL SWEEP COMPLETE
============================================================

In [27]:
# ============================================================
# E2 — SAVE FROZEN PAULI RESULTS
# ============================================================

e2_metrics_path = (
    RESULTS_DIR / "e2_pauli_metrics.csv"
)

e2_metrics.to_csv(
    e2_metrics_path,
    index=False
)

# ------------------------------------------------------------
# E2 vs E0
# ------------------------------------------------------------

e2_comparison = e2_metrics.copy()

e2_comparison["accuracy_gap"] = (
    ideal_accuracy - e2_comparison["accuracy"]
)

e2_comparison["f1_gap"] = (
    ideal_f1 - e2_comparison["f1"]
)

e2_comparison["accuracy_relative_gap"] = (
    abs(ideal_accuracy - e2_comparison["accuracy"])
    / ideal_accuracy
)

e2_comparison["f1_relative_gap"] = (
    abs(ideal_f1 - e2_comparison["f1"])
    / ideal_f1
)

e2_comparison_path = (
    RESULTS_DIR / "e2_pauli_comparison.csv"
)

e2_comparison.to_csv(
    e2_comparison_path,
    index=False
)

print("=" * 60)
print("E2 BASELINE FROZEN")
print("=" * 60)

print("\nSaved:")
print(e2_metrics_path)
print(e2_comparison_path)

display(
    e2_comparison[
        [
            "noise_level",
            "accuracy",
            "f1",
            "accuracy_gap",
            "f1_gap",
            "accuracy_relative_gap",
            "f1_relative_gap"
        ]
    ]
)

print("\nValidation: E2 PAULI RESULTS SAVED")

NameError: name 'e2_metrics' is not defined

In [28]:
# ============================================================
# E2.4 — CREATE E2 METRICS + FREEZE RESULTS
# ============================================================

# ------------------------------------------------------------
# Create DataFrame from completed E2 sweep
# ------------------------------------------------------------

e2_metrics = pd.DataFrame(e2_results)

print("=" * 60)
print("E2 PAULI NOISE RESULTS")
print("=" * 60)

display(
    e2_metrics[
        [
            "noise_level",
            "accuracy",
            "precision",
            "recall",
            "f1"
        ]
    ]
)

# ------------------------------------------------------------
# Save raw E2 metrics
# ------------------------------------------------------------

e2_metrics_path = (
    RESULTS_DIR / "e2_pauli_metrics.csv"
)

e2_metrics.to_csv(
    e2_metrics_path,
    index=False
)

# ------------------------------------------------------------
# E2 vs E0 comparison
# ------------------------------------------------------------

e2_comparison = e2_metrics.copy()

e2_comparison["accuracy_gap"] = (
    ideal_accuracy -
    e2_comparison["accuracy"]
)

e2_comparison["f1_gap"] = (
    ideal_f1 -
    e2_comparison["f1"]
)

e2_comparison["accuracy_relative_gap"] = (
    abs(
        ideal_accuracy -
        e2_comparison["accuracy"]
    )
    / ideal_accuracy
)

e2_comparison["f1_relative_gap"] = (
    abs(
        ideal_f1 -
        e2_comparison["f1"]
    )
    / ideal_f1
)

# ------------------------------------------------------------
# Save comparison
# ------------------------------------------------------------

e2_comparison_path = (
    RESULTS_DIR / "e2_pauli_comparison.csv"
)

e2_comparison.to_csv(
    e2_comparison_path,
    index=False
)

# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

print("\n" + "=" * 60)
print("E2 BASELINE FROZEN")
print("=" * 60)

print("\nSaved:")
print(e2_metrics_path)
print(e2_comparison_path)

print("\nE2 vs E0:")

display(
    e2_comparison[
        [
            "noise_level",
            "accuracy",
            "f1",
            "accuracy_gap",
            "f1_gap",
            "accuracy_relative_gap",
            "f1_relative_gap"
        ]
    ]
)

print("\nValidation: E2 PAULI RESULTS SAVED")

============================================================
E2 PAULI NOISE RESULTS
============================================================

   noise_level  accuracy  precision  recall        f1
0        0.001     0.850   0.836538    0.87  0.852941
1        0.005     0.850   0.836538    0.87  0.852941
2        0.010     0.850   0.836538    0.87  0.852941
3        0.020     0.835   0.813084    0.87  0.840580
4        0.050     0.835   0.819048    0.86  0.839024

============================================================
E2 BASELINE FROZEN
============================================================

Saved:
C:\Users\heart\quantum_6g_ai\results\e2_pauli_metrics.csv
C:\Users\heart\quantum_6g_ai\results\e2_pauli_comparison.csv

E2 vs E0:

,noise_level,accuracy,f1,accuracy_gap,f1_gap,accuracy_relative_gap,f1_relative_gap
0,0.001,0.850,0.852941,0.000,0.000000,0.000000,0.000000
1,0.005,0.850,0.852941,0.000,0.000000,0.000000,0.000000
2,0.010,0.850,0.852941,0.000,0.000000,0.000000,0.000000
3,0.020,0.835,0.840580,0.015,0.012361,0.017647,0.014493
4,0.050,0.835,0.839024,0.015,0.013917,0.017647,0.016316

Validation: E2 PAULI RESULTS SAVED

In [29]:
# ============================================================
# E3.1 — CONTROLLED READOUT NOISE MODEL
# ============================================================

from qiskit_aer.noise import NoiseModel, ReadoutError


E3_SHOTS = 1024
E3_SEED = 42

E3_NOISE_LEVELS = [
    0.001,
    0.005,
    0.010,
    0.020,
    0.050
]


def build_e3_readout_noise(noise_level):
    """
    Build a readout-only noise model.

    No quantum gate noise is applied.
    Only measurement/readout errors are introduced.

    Readout transition matrix:

        P(measured 0 | true 0) = 1-p
        P(measured 1 | true 0) = p

        P(measured 0 | true 1) = p
        P(measured 1 | true 1) = 1-p
    """

    if not 0.0 <= noise_level <= 1.0:
        raise ValueError(
            f"noise_level must be between 0 and 1, got {noise_level}"
        )

    noise_model = NoiseModel()

    readout_error = ReadoutError([
        [1.0 - noise_level, noise_level],
        [noise_level, 1.0 - noise_level]
    ])

    noise_model.add_all_qubit_readout_error(
        readout_error
    )

    return noise_model


print("=" * 60)
print("E3 READOUT NOISE MODEL")
print("=" * 60)

print("Shots        :", E3_SHOTS)
print("Base seed    :", E3_SEED)
print("Noise levels :", E3_NOISE_LEVELS)

e3_noise_models = {}

for level in E3_NOISE_LEVELS:

    model = build_e3_readout_noise(level)

    e3_noise_models[level] = model

    print("\nNoise level:", level)
    print(model)

print("\nValidation: E3 READOUT NOISE MODELS CREATED")

============================================================
E3 READOUT NOISE MODEL
============================================================
Shots        : 1024
Base seed    : 42
Noise levels : [0.001, 0.005, 0.01, 0.02, 0.05]

Noise level: 0.001
NoiseModel:
  Basis gates: ['cx', 'id', 'rz', 'sx']
  Instructions with noise: ['measure']
  All-qubits errors: ['measure']

Noise level: 0.005
NoiseModel:
  Basis gates: ['cx', 'id', 'rz', 'sx']
  Instructions with noise: ['measure']
  All-qubits errors: ['measure']

Noise level: 0.01
NoiseModel:
  Basis gates: ['cx', 'id', 'rz', 'sx']
  Instructions with noise: ['measure']
  All-qubits errors: ['measure']

Noise level: 0.02
NoiseModel:
  Basis gates: ['cx', 'id', 'rz', 'sx']
  Instructions with noise: ['measure']
  All-qubits errors: ['measure']

Noise level: 0.05
NoiseModel:
  Basis gates: ['cx', 'id', 'rz', 'sx']
  Instructions with noise: ['measure']
  All-qubits errors: ['measure']

Validation: E3 READOUT NOISE MODELS CREATED

In [30]:
# ============================================================
# E3.2 — SINGLE-SAMPLE READOUT NOISE SANITY CHECK
# ============================================================

def vqc_probability_e3(
    feature_angles,
    parameter_values,
    noise_level,
    shots=1024,
    seed=42
):
    """
    Run frozen VQC with readout noise only.
    """

    circuit = build_vqc(
        feature_angles,
        n_qubits=N_QUBITS,
        n_layers=N_LAYERS
    )

    parameter_dict = {
        vqc_parameters[i]: float(parameter_values[i])
        for i in range(len(parameter_values))
    }

    circuit = circuit.assign_parameters(
        parameter_dict
    )

    circuit.measure_all()

    # Readout-only noise
    noise_model = build_e3_readout_noise(
        noise_level
    )

    noisy_simulator = AerSimulator(
        noise_model=noise_model
    )

    compiled = transpile(
        circuit,
        noisy_simulator,
        optimization_level=1
    )

    job = noisy_simulator.run(
        compiled,
        shots=shots,
        seed_simulator=seed
    )

    result = job.result()
    counts = result.get_counts()

    p1 = 0.0

    for bitstring, count in counts.items():

        q0_bit = int(bitstring[-1])

        if q0_bit == 1:
            p1 += count / shots

    return p1


# ------------------------------------------------------------
# Test sample 0
# ------------------------------------------------------------

sample_index = 0

feature_angles = X_test[sample_index]
true_label = y_test[sample_index]

print("=" * 60)
print("E3 SINGLE-SAMPLE READOUT NOISE CHECK")
print("=" * 60)

print("Sample index :", sample_index)
print("True label   :", true_label)
print("Shots        :", E3_SHOTS)

print("\nResults:")

for level in E3_NOISE_LEVELS:

    probability = vqc_probability_e3(
        feature_angles,
        trained_theta,
        noise_level=level,
        shots=E3_SHOTS,
        seed=E3_SEED
    )

    prediction = int(
        probability >= 0.5
    )

    print(
        f"Noise={level:0.3f} | "
        f"P(y=1)={probability:.6f} | "
        f"Prediction={prediction}"
    )

print("\nValidation: E3 SINGLE-SAMPLE CHECK COMPLETE")

============================================================
E3 SINGLE-SAMPLE READOUT NOISE CHECK
============================================================
Sample index : 0
True label   : 1
Shots        : 1024

Results:
Noise=0.001 | P(y=1)=0.995117 | Prediction=1
Noise=0.005 | P(y=1)=0.991211 | Prediction=1
Noise=0.010 | P(y=1)=0.985352 | Prediction=1
Noise=0.020 | P(y=1)=0.976562 | Prediction=1
Noise=0.050 | P(y=1)=0.950195 | Prediction=1

Validation: E3 SINGLE-SAMPLE CHECK COMPLETE

In [31]:
# ============================================================
# E3.3 — FULL READOUT NOISE SWEEP
# ============================================================

def vqc_predict_proba_e3(
    X_data,
    parameter_values,
    noise_level,
    shots=1024,
    seed=42
):
    """
    Generate VQC probabilities under readout-only noise.
    """

    probabilities = []

    for i, feature_angles in enumerate(X_data):

        sample_seed = seed + i

        p1 = vqc_probability_e3(
            feature_angles,
            parameter_values,
            noise_level=noise_level,
            shots=shots,
            seed=sample_seed
        )

        probabilities.append(p1)

    return np.asarray(probabilities)


# ------------------------------------------------------------
# Full E3 experiment
# ------------------------------------------------------------

e3_results = []

print("=" * 60)
print("E3 FULL READOUT NOISE EXPERIMENT")
print("=" * 60)

print("Samples       :", len(X_test))
print("Shots         :", E3_SHOTS)
print("Base seed     :", E3_SEED)
print("Noise levels  :", E3_NOISE_LEVELS)

for noise_level in E3_NOISE_LEVELS:

    print("\n" + "-" * 60)
    print(f"Running noise level = {noise_level:.3f}")
    print("-" * 60)

    probabilities = vqc_predict_proba_e3(
        X_test,
        trained_theta,
        noise_level=noise_level,
        shots=E3_SHOTS,
        seed=E3_SEED
    )

    predictions = (
        probabilities >= 0.5
    ).astype(int)

    accuracy = accuracy_score(
        y_test,
        predictions
    )

    precision = precision_score(
        y_test,
        predictions,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        predictions,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        predictions,
        zero_division=0
    )

    cm = confusion_matrix(
        y_test,
        predictions
    )

    print("Accuracy  :", round(accuracy, 6))
    print("Precision :", round(precision, 6))
    print("Recall    :", round(recall, 6))
    print("F1        :", round(f1, 6))

    print("\nConfusion Matrix:")
    print(cm)

    e3_results.append({
        "experiment_id": "E3",
        "environment": "controlled_noisy_simulation",
        "backend": "AerSimulator",
        "noise_type": "readout",
        "noise_level": noise_level,
        "seed": E3_SEED,
        "shots": E3_SHOTS,
        "n_samples": len(X_test),
        "n_qubits": N_QUBITS,
        "vqc_layers": N_LAYERS,
        "n_parameters": len(trained_theta),
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    })


print("\n" + "=" * 60)
print("E3 FULL SWEEP COMPLETE")
print("=" * 60)

============================================================
E3 FULL READOUT NOISE EXPERIMENT
============================================================
Samples       : 200
Shots         : 1024
Base seed     : 42
Noise levels  : [0.001, 0.005, 0.01, 0.02, 0.05]

------------------------------------------------------------
Running noise level = 0.001
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.005
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.010
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.020
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.050
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

============================================================
E3 FULL SWEEP COMPLETE
============================================================

In [32]:
# ============================================================
# E3.4 — E3 RESULT TABLE
# ============================================================

e3_metrics = pd.DataFrame(
    e3_results
)

print("=" * 60)
print("E3 READOUT NOISE RESULTS")
print("=" * 60)

display(
    e3_metrics[
        [
            "noise_level",
            "accuracy",
            "precision",
            "recall",
            "f1"
        ]
    ]
)

print("\nValidation: E3 RESULTS GENERATED")

============================================================
E3 READOUT NOISE RESULTS
============================================================

   noise_level  accuracy  precision  recall        f1
0        0.001      0.85   0.836538    0.87  0.852941
1        0.005      0.85   0.836538    0.87  0.852941
2        0.010      0.85   0.836538    0.87  0.852941
3        0.020      0.85   0.836538    0.87  0.852941
4        0.050      0.85   0.836538    0.87  0.852941

Validation: E3 RESULTS GENERATED

In [33]:
# ============================================================
# E3.5 — FREEZE READOUT NOISE RESULTS
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# Recreate E3 metrics table
# ------------------------------------------------------------

e3_metrics = pd.DataFrame(e3_results)

# ------------------------------------------------------------
# Add comparison against E0
# ------------------------------------------------------------

e3_comparison = e3_metrics[
    [
        "noise_level",
        "accuracy",
        "f1"
    ]
].copy()

e3_comparison["accuracy_gap"] = (
    ideal_accuracy -
    e3_comparison["accuracy"]
)

e3_comparison["f1_gap"] = (
    ideal_f1 -
    e3_comparison["f1"]
)

e3_comparison["accuracy_relative_gap"] = (
    e3_comparison["accuracy_gap"] /
    ideal_accuracy
)

e3_comparison["f1_relative_gap"] = (
    e3_comparison["f1_gap"] /
    ideal_f1
)

# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

e3_metrics_path = (
    RESULTS_DIR /
    "e3_readout_metrics.csv"
)

e3_comparison_path = (
    RESULTS_DIR /
    "e3_readout_comparison.csv"
)

e3_metrics.to_csv(
    e3_metrics_path,
    index=False
)

e3_comparison.to_csv(
    e3_comparison_path,
    index=False
)

# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print("=" * 60)
print("E3 READOUT NOISE RESULTS")
print("=" * 60)

display(
    e3_metrics[
        [
            "noise_level",
            "accuracy",
            "precision",
            "recall",
            "f1"
        ]
    ]
)

print("\n" + "=" * 60)
print("E3 VS E0")
print("=" * 60)

display(
    e3_comparison
)

print("\nSaved:")
print(e3_metrics_path)
print(e3_comparison_path)

print("\nValidation: E3 READOUT RESULTS SAVED")

============================================================
E3 READOUT NOISE RESULTS
============================================================

   noise_level  accuracy  precision  recall        f1
0        0.001      0.85   0.836538    0.87  0.852941
1        0.005      0.85   0.836538    0.87  0.852941
2        0.010      0.85   0.836538    0.87  0.852941
3        0.020      0.85   0.836538    0.87  0.852941
4        0.050      0.85   0.836538    0.87  0.852941

============================================================
E3 VS E0
============================================================

,noise_level,accuracy,f1,accuracy_gap,f1_gap,accuracy_relative_gap,f1_relative_gap
0,0.001,0.85,0.852941,0.0,0.0,0.0,0.0
1,0.005,0.85,0.852941,0.0,0.0,0.0,0.0
2,0.010,0.85,0.852941,0.0,0.0,0.0,0.0
3,0.020,0.85,0.852941,0.0,0.0,0.0,0.0
4,0.050,0.85,0.852941,0.0,0.0,0.0,0.0

Saved:
C:\Users\heart\quantum_6g_ai\results\e3_readout_metrics.csv
C:\Users\heart\quantum_6g_ai\results\e3_readout_comparison.csv

Validation: E3 READOUT RESULTS SAVED

In [35]:
# ============================================================
# E4.1 — COMBINED GATE + READOUT NOISE MODEL
# ============================================================

from qiskit_aer.noise import (
    NoiseModel,
    depolarizing_error,
    ReadoutError
)

E4_SHOTS = 1024
E4_SEED = 42

E4_NOISE_LEVELS = [
    0.001,
    0.005,
    0.010,
    0.020,
    0.050
]


def build_e4_combined_noise(noise_level):
    """
    E4 combined noise model.

    1Q gates:
        Depolarizing noise on RY and RZ

    2Q gates:
        Depolarizing noise on CX

    Measurement:
        Symmetric readout error

    The same noise level is used for
    gate noise and readout noise.
    """

    if not 0.0 <= noise_level <= 1.0:
        raise ValueError(
            "noise_level must be between 0 and 1"
        )

    noise_model = NoiseModel()

    # --------------------------------------------------------
    # 1-qubit gate noise
    # --------------------------------------------------------

    error_1q = depolarizing_error(
        noise_level,
        1
    )

    noise_model.add_all_qubit_quantum_error(
        error_1q,
        ["ry", "rz"]
    )

    # --------------------------------------------------------
    # 2-qubit gate noise
    # --------------------------------------------------------

    error_2q = depolarizing_error(
        noise_level,
        2
    )

    noise_model.add_all_qubit_quantum_error(
        error_2q,
        ["cx"]
    )

    # --------------------------------------------------------
    # Readout noise
    # --------------------------------------------------------

    readout_error = ReadoutError([
        [
            1.0 - noise_level,
            noise_level
        ],
        [
            noise_level,
            1.0 - noise_level
        ]
    ])

    noise_model.add_all_qubit_readout_error(
        readout_error
    )

    return noise_model


print("=" * 60)
print("E4 COMBINED NOISE MODEL")
print("=" * 60)

print("Shots        :", E4_SHOTS)
print("Base seed    :", E4_SEED)
print("Noise levels :", E4_NOISE_LEVELS)

for level in E4_NOISE_LEVELS:

    print("\n" + "-" * 60)
    print(f"Noise level: {level:.3f}")
    print("-" * 60)

    model = build_e4_combined_noise(level)

    print(model)


print("\nValidation: E4 COMBINED NOISE MODELS CREATED")

============================================================
E4 COMBINED NOISE MODEL
============================================================
Shots        : 1024
Base seed    : 42
Noise levels : [0.001, 0.005, 0.01, 0.02, 0.05]

------------------------------------------------------------
Noise level: 0.001
------------------------------------------------------------
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'measure', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx', 'measure']

------------------------------------------------------------
Noise level: 0.005
------------------------------------------------------------
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'measure', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx', 'measure']

------------------------------------------------------------
Noise level: 0.010
------------------------------------------------------------
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'measure', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx', 'measure']

------------------------------------------------------------
Noise level: 0.020
------------------------------------------------------------
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'measure', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx', 'measure']

------------------------------------------------------------
Noise level: 0.050
------------------------------------------------------------
NoiseModel:
  Basis gates: ['cx', 'id', 'ry', 'rz', 'sx']
  Instructions with noise: ['cx', 'ry', 'measure', 'rz']
  All-qubits errors: ['ry', 'rz', 'cx', 'measure']

Validation: E4 COMBINED NOISE MODELS CREATED

In [36]:
# ============================================================
# E4.2 — SINGLE-SAMPLE COMBINED NOISE SANITY CHECK
# ============================================================

def vqc_probability_e4(
    feature_angles,
    parameter_values,
    noise_level,
    shots=1024,
    seed=42
):
    """
    VQC probability under combined gate + readout noise.
    """

    circuit = build_vqc(
        feature_angles,
        n_qubits=N_QUBITS,
        n_layers=N_LAYERS
    )

    parameter_dict = {
        vqc_parameters[i]: float(parameter_values[i])
        for i in range(len(parameter_values))
    }

    circuit = circuit.assign_parameters(
        parameter_dict
    )

    circuit.measure_all()

    noise_model = build_e4_combined_noise(
        noise_level
    )

    noisy_simulator = AerSimulator(
        noise_model=noise_model
    )

    compiled = transpile(
        circuit,
        noisy_simulator,
        optimization_level=1
    )

    job = noisy_simulator.run(
        compiled,
        shots=shots,
        seed_simulator=seed
    )

    result = job.result()
    counts = result.get_counts()

    p1 = 0.0

    for bitstring, count in counts.items():

        q0_bit = int(
            bitstring[-1]
        )

        if q0_bit == 1:
            p1 += count / shots

    return p1


# ------------------------------------------------------------
# Test sample
# ------------------------------------------------------------

sample_index = 0

feature_angles = X_test[sample_index]
true_label = y_test[sample_index]

print("=" * 60)
print("E4 SINGLE-SAMPLE COMBINED NOISE CHECK")
print("=" * 60)

print("Sample index :", sample_index)
print("True label   :", true_label)
print("Shots        :", E4_SHOTS)

print("\nResults:")

for level in E4_NOISE_LEVELS:

    probability = vqc_probability_e4(
        feature_angles,
        trained_theta,
        noise_level=level,
        shots=E4_SHOTS,
        seed=E4_SEED
    )

    prediction = int(
        probability >= 0.5
    )

    print(
        f"Noise={level:0.3f} | "
        f"P(y=1)={probability:.6f} | "
        f"Prediction={prediction}"
    )

print(
    "\nValidation: "
    "E4 SINGLE-SAMPLE CHECK COMPLETE"
)

============================================================
E4 SINGLE-SAMPLE COMBINED NOISE CHECK
============================================================
Sample index : 0
True label   : 1
Shots        : 1024

Results:
Noise=0.001 | P(y=1)=0.989258 | Prediction=1
Noise=0.005 | P(y=1)=0.963867 | Prediction=1
Noise=0.010 | P(y=1)=0.942383 | Prediction=1
Noise=0.020 | P(y=1)=0.898438 | Prediction=1
Noise=0.050 | P(y=1)=0.784180 | Prediction=1

Validation: E4 SINGLE-SAMPLE CHECK COMPLETE

In [37]:
# ============================================================
# E4.3 — FULL COMBINED NOISE SWEEP
# ============================================================

def vqc_predict_proba_e4(
    X_data,
    parameter_values,
    noise_level,
    shots=1024,
    seed=42
):
    """
    Generate VQC probabilities under combined
    gate + readout noise.
    """

    probabilities = []

    for i, feature_angles in enumerate(X_data):

        sample_seed = seed + i

        p1 = vqc_probability_e4(
            feature_angles,
            parameter_values,
            noise_level=noise_level,
            shots=shots,
            seed=sample_seed
        )

        probabilities.append(p1)

    return np.asarray(probabilities)


# ------------------------------------------------------------
# Full E4 experiment
# ------------------------------------------------------------

e4_results = []

print("=" * 60)
print("E4 FULL COMBINED NOISE EXPERIMENT")
print("=" * 60)

print("Samples       :", len(X_test))
print("Shots         :", E4_SHOTS)
print("Base seed     :", E4_SEED)
print("Noise levels  :", E4_NOISE_LEVELS)

for noise_level in E4_NOISE_LEVELS:

    print("\n" + "-" * 60)
    print(f"Running noise level = {noise_level:.3f}")
    print("-" * 60)

    probabilities = vqc_predict_proba_e4(
        X_test,
        trained_theta,
        noise_level=noise_level,
        shots=E4_SHOTS,
        seed=E4_SEED
    )

    predictions = (
        probabilities >= 0.5
    ).astype(int)

    accuracy = accuracy_score(
        y_test,
        predictions
    )

    precision = precision_score(
        y_test,
        predictions,
        zero_division=0
    )

    recall = recall_score(
        y_test,
        predictions,
        zero_division=0
    )

    f1 = f1_score(
        y_test,
        predictions,
        zero_division=0
    )

    cm = confusion_matrix(
        y_test,
        predictions
    )

    print("Accuracy  :", round(accuracy, 6))
    print("Precision :", round(precision, 6))
    print("Recall    :", round(recall, 6))
    print("F1        :", round(f1, 6))

    print("\nConfusion Matrix:")
    print(cm)

    e4_results.append({
        "experiment_id": "E4",
        "environment": "controlled_noisy_simulation",
        "backend": "AerSimulator",
        "noise_type": "combined_depolarizing_readout",
        "noise_level": noise_level,
        "seed": E4_SEED,
        "shots": E4_SHOTS,
        "n_samples": len(X_test),
        "n_qubits": N_QUBITS,
        "vqc_layers": N_LAYERS,
        "n_parameters": len(trained_theta),
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    })


print("\n" + "=" * 60)
print("E4 FULL SWEEP COMPLETE")
print("=" * 60)

============================================================
E4 FULL COMBINED NOISE EXPERIMENT
============================================================
Samples       : 200
Shots         : 1024
Base seed     : 42
Noise levels  : [0.001, 0.005, 0.01, 0.02, 0.05]

------------------------------------------------------------
Running noise level = 0.001
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.005
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.010
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.020
------------------------------------------------------------
Accuracy  : 0.84
Precision : 0.820755
Recall    : 0.87
F1        : 0.84466

Confusion Matrix:
[[81 19]
 [13 87]]

------------------------------------------------------------
Running noise level = 0.050
------------------------------------------------------------
Accuracy  : 0.85
Precision : 0.836538
Recall    : 0.87
F1        : 0.852941

Confusion Matrix:
[[83 17]
 [13 87]]

============================================================
E4 FULL SWEEP COMPLETE
============================================================

In [1]:
# ============================================================
# E4.5 — FREEZE COMBINED NOISE RESULTS
# ============================================================

e4_metrics = pd.DataFrame(
    e4_results
)

# ------------------------------------------------------------
# Compare against E0
# ------------------------------------------------------------

e4_comparison = e4_metrics[
    [
        "noise_level",
        "accuracy",
        "precision",
        "recall",
        "f1"
    ]
].copy()

e4_comparison["accuracy_gap"] = (
    ideal_accuracy -
    e4_comparison["accuracy"]
)

e4_comparison["f1_gap"] = (
    ideal_f1 -
    e4_comparison["f1"]
)

e4_comparison["accuracy_relative_gap"] = (
    e4_comparison["accuracy_gap"] /
    ideal_accuracy
)

e4_comparison["f1_relative_gap"] = (
    e4_comparison["f1_gap"] /
    ideal_f1
)

# ------------------------------------------------------------
# Save files
# ------------------------------------------------------------

e4_metrics_path = (
    RESULTS_DIR /
    "e4_combined_metrics.csv"
)

e4_comparison_path = (
    RESULTS_DIR /
    "e4_combined_comparison.csv"
)

e4_metrics.to_csv(
    e4_metrics_path,
    index=False
)

e4_comparison.to_csv(
    e4_comparison_path,
    index=False
)

# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print("=" * 60)
print("E4 COMBINED NOISE RESULTS")
print("=" * 60)

display(
    e4_metrics[
        [
            "noise_level",
            "accuracy",
            "precision",
            "recall",
            "f1"
        ]
    ]
)

print("\n" + "=" * 60)
print("E4 VS E0")
print("=" * 60)

display(
    e4_comparison
)

print("\nSaved:")
print(e4_metrics_path)
print(e4_comparison_path)

print("\nValidation: E4 COMBINED RESULTS SAVED")

NameError: name 'pd' is not defined

In [2]:
# ============================================================
# E4.5 — FREEZE COMBINED NOISE RESULTS
# ============================================================

import pandas as pd
from pathlib import Path

# ------------------------------------------------------------
# Project paths
# ------------------------------------------------------------

PROJECT_ROOT = Path(
    r"C:\Users\heart\quantum_6g_ai"
)

RESULTS_DIR = PROJECT_ROOT / "results"

# ------------------------------------------------------------
# E0 reference metrics
# ------------------------------------------------------------

ideal_accuracy = 0.85
ideal_f1 = 0.8529411764705882

# ------------------------------------------------------------
# Reconstruct E4 results from completed experiment
# ------------------------------------------------------------

e4_results = [
    {
        "experiment_id": "E4",
        "environment": "controlled_noisy_simulation",
        "backend": "AerSimulator",
        "noise_type": "combined_depolarizing_readout",
        "noise_level": 0.001,
        "seed": 42,
        "shots": 1024,
        "n_samples": 200,
        "n_qubits": 4,
        "vqc_layers": 2,
        "n_parameters": 16,
        "accuracy": 0.85,
        "precision": 0.836538,
        "recall": 0.87,
        "f1": 0.852941
    },
    {
        "experiment_id": "E4",
        "environment": "controlled_noisy_simulation",
        "backend": "AerSimulator",
        "noise_type": "combined_depolarizing_readout",
        "noise_level": 0.005,
        "seed": 42,
        "shots": 1024,
        "n_samples": 200,
        "n_qubits": 4,
        "vqc_layers": 2,
        "n_parameters": 16,
        "accuracy": 0.85,
        "precision": 0.836538,
        "recall": 0.87,
        "f1": 0.852941
    },
    {
        "experiment_id": "E4",
        "environment": "controlled_noisy_simulation",
        "backend": "AerSimulator",
        "noise_type": "combined_depolarizing_readout",
        "noise_level": 0.010,
        "seed": 42,
        "shots": 1024,
        "n_samples": 200,
        "n_qubits": 4,
        "vqc_layers": 2,
        "n_parameters": 16,
        "accuracy": 0.85,
        "precision": 0.836538,
        "recall": 0.87,
        "f1": 0.852941
    },
    {
        "experiment_id": "E4",
        "environment": "controlled_noisy_simulation",
        "backend": "AerSimulator",
        "noise_type": "combined_depolarizing_readout",
        "noise_level": 0.020,
        "seed": 42,
        "shots": 1024,
        "n_samples": 200,
        "n_qubits": 4,
        "vqc_layers": 2,
        "n_parameters": 16,
        "accuracy": 0.84,
        "precision": 0.820755,
        "recall": 0.87,
        "f1": 0.844660
    },
    {
        "experiment_id": "E4",
        "environment": "controlled_noisy_simulation",
        "backend": "AerSimulator",
        "noise_type": "combined_depolarizing_readout",
        "noise_level": 0.050,
        "seed": 42,
        "shots": 1024,
        "n_samples": 200,
        "n_qubits": 4,
        "vqc_layers": 2,
        "n_parameters": 16,
        "accuracy": 0.85,
        "precision": 0.836538,
        "recall": 0.87,
        "f1": 0.852941
    }
]

# ------------------------------------------------------------
# Create DataFrame
# ------------------------------------------------------------

e4_metrics = pd.DataFrame(
    e4_results
)

# ------------------------------------------------------------
# Comparison against E0
# ------------------------------------------------------------

e4_comparison = e4_metrics[
    [
        "noise_level",
        "accuracy",
        "precision",
        "recall",
        "f1"
    ]
].copy()

e4_comparison["accuracy_gap"] = (
    ideal_accuracy -
    e4_comparison["accuracy"]
)

e4_comparison["f1_gap"] = (
    ideal_f1 -
    e4_comparison["f1"]
)

e4_comparison["accuracy_relative_gap"] = (
    e4_comparison["accuracy_gap"] /
    ideal_accuracy
)

e4_comparison["f1_relative_gap"] = (
    e4_comparison["f1_gap"] /
    ideal_f1
)

# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

e4_metrics_path = (
    RESULTS_DIR /
    "e4_combined_metrics.csv"
)

e4_comparison_path = (
    RESULTS_DIR /
    "e4_combined_comparison.csv"
)

e4_metrics.to_csv(
    e4_metrics_path,
    index=False
)

e4_comparison.to_csv(
    e4_comparison_path,
    index=False
)

# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print("=" * 60)
print("E4 COMBINED NOISE RESULTS")
print("=" * 60)

display(
    e4_metrics[
        [
            "noise_level",
            "accuracy",
            "precision",
            "recall",
            "f1"
        ]
    ]
)

print("\n" + "=" * 60)
print("E4 VS E0")
print("=" * 60)

display(e4_comparison)

print("\nSaved:")
print(e4_metrics_path)
print(e4_comparison_path)

print("\nValidation: E4 COMBINED RESULTS SAVED")

============================================================
E4 COMBINED NOISE RESULTS
============================================================

   noise_level  accuracy  precision  recall        f1
0        0.001      0.85   0.836538    0.87  0.852941
1        0.005      0.85   0.836538    0.87  0.852941
2        0.010      0.85   0.836538    0.87  0.852941
3        0.020      0.84   0.820755    0.87  0.844660
4        0.050      0.85   0.836538    0.87  0.852941

============================================================
E4 VS E0
============================================================

,noise_level,accuracy,precision,recall,f1,accuracy_gap,f1_gap,accuracy_relative_gap,f1_relative_gap
0,0.001,0.85,0.836538,0.87,0.852941,0.00,1.764706e-07,0.000000,2.068966e-07
1,0.005,0.85,0.836538,0.87,0.852941,0.00,1.764706e-07,0.000000,2.068966e-07
2,0.010,0.85,0.836538,0.87,0.852941,0.00,1.764706e-07,0.000000,2.068966e-07
3,0.020,0.84,0.820755,0.87,0.844660,0.01,8.281176e-03,0.011765,9.708966e-03
4,0.050,0.85,0.836538,0.87,0.852941,0.00,1.764706e-07,0.000000,2.068966e-07

Saved:
C:\Users\heart\quantum_6g_ai\results\e4_combined_metrics.csv
C:\Users\heart\quantum_6g_ai\results\e4_combined_comparison.csv

Validation: E4 COMBINED RESULTS SAVED